"use strict";

const characters = [
    "Alisa", "Anna", "Armour", "Asuka", "Azucena", "Bryan", "Claudio", "Clive",
    "Devil", "Dragunov", "Eddy", "Fahkumram", "Feng", "Heihachi", "Hwoarang",
    "Jack", "Jin", "Jun", "Kazuya", "King", "Kuma", "Lars", "Law", "Lee",
    "Leo", "Leroy", "Lidia", "Lili", "Nina", "Panda", "Paul", "Raven",
    "Reina", "Shaheen", "Steve", "Victor", "Xiaoyu", "Yoshimitsu", "Zafina",
];

/**
 * Fetches character data from external JSON files and renders tables.
 * @param {string} character - The name of the character selected.
 * @param {string} containerID - The ID of the div (playerOneContainer or playerTwoContainer).
 */
async function renderTables(character, containerID) {
    const container = document.getElementById(containerID);
    if (!container) return;

    container.innerHTML = "<p>Loading data...</p>";

    try {
        // Fetches the file based on character name. 
        const response = await fetch(`./char_data/${character}.json`);
        
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const characterData = await response.json();
        container.innerHTML = ""; // Clear loading message

        // Section titles mapping
        const sectionTitles = [
            "Key Terminology",
            "Important Moves",
            (character === "King" || character === "Lars") ? "Command Grabs" : "Defensive Options"
        ];

        // Process move_tables from the fetched JSON
        characterData.move_tables.forEach((tableData, index) => {
            const tableWrapper = document.createElement("div");
            tableWrapper.className = "character-table-section";

            const heading = document.createElement("h2");
            heading.innerText = sectionTitles[index] || "Additional Data";
            tableWrapper.appendChild(heading);

            const table = document.createElement("table");

            // Build Headers
            const headerRow = document.createElement("tr");
            tableData.headers.forEach(headerText => {
                const th = document.createElement("th");
                th.innerHTML = headerText;
                headerRow.appendChild(th);
            });
            table.appendChild(headerRow);

            // Build Rows
            tableData.rows.forEach(rowData => {
                const tr = document.createElement("tr");
                rowData.forEach(cellText => {
                    const td = document.createElement("td");
                    // Add notation class if the cell contains notation markers
                    if (cellText.includes("notation")) {
                        td.classList.add("notation");
                    }
                    td.innerHTML = cellText;
                    tr.appendChild(td);
                });
                table.appendChild(tr);
            });

            tableWrapper.appendChild(table);
            container.appendChild(tableWrapper);
        });

    } catch (error) {
        console.error("Could not fetch character data:", error);
        container.innerHTML = `<p class="error">Data for ${character} could not be loaded. Please ensure ${character}.json exists in the /char_data/ folder.</p>`;
    }
}

async function showMatch() {
    const p1 = document.getElementById("playerOneSelection").value;
    const p2 = document.getElementById("playerTwoSelection").value;
    const videoContainer = document.getElementById("videoContainer");
    
    videoContainer.innerHTML = "<p>Finding best match replay...</p>";

    // Priority 1: Check your local 'matches' library (if included in your project)
    if (typeof matches !== 'undefined' && matches[p1] && matches[p1][p2] && matches[p1][p2].length > 0) {
        displayVideo(matches[p1][p2][0]);
        return;
    }

    // Priority 2: Fallback to YouTube API search
    try {
        await fetchYouTubeMatch(p1, p2);
    } catch (error) {
        videoContainer.innerHTML = "<p>Error loading video.</p>";
        console.error(error);
    }
}

/*async function fetchYouTubeMatch(p1, p2) {
    const API_KEY = 'YOUR_YOUTUBE_API_KEY';
    const query = `Tekken 8 ${p1} vs ${p2} pro match`;
    const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=1&q=${encodeURIComponent(query)}&type=video&key=${API_KEY}`;

    const response = await fetch(url);
    const data = await response.json();

    if (data.items && data.items.length > 0) {
        const videoId = data.items[0].id.videoId;
        displayVideo(`https://www.youtube.com/embed/${videoId}`);
    } else {
        document.getElementById("videoContainer").innerHTML = "<p>No matches found for this pair.</p>";
    }
}*/

function displayVideo(url) {
    const videoContainer = document.getElementById("videoContainer");
    videoContainer.innerHTML = ""; 
    const iframe = document.createElement("iframe");
    iframe.width = "560";
    iframe.height = "315";
    iframe.src = `${url}?autoplay=1`;
    iframe.allowFullscreen = true;
    iframe.allow = "autoplay; encrypted-media; fullscreen";
    videoContainer.appendChild(iframe);
}

// Event Listeners initialization
document.addEventListener("DOMContentLoaded", () => {
    const p1Select = document.getElementById("playerOneSelection");
    const p2Select = document.getElementById("playerTwoSelection");
    const findMatchBtn = document.getElementById("findMatchButton");

    p1Select.addEventListener("change", (e) => {
        renderTables(e.target.value, "playerOneContainer");
    });

    p2Select.addEventListener("change", (e) => {
        renderTables(e.target.value, "playerTwoContainer");
    });

    if (findMatchBtn) {
        findMatchBtn.addEventListener("click", showMatch);
    }
});

const matches = {
  Alisa: {
    Alisa: ["https://www.youtube.com/embed/u30q2WboW1o"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/vL8K4zJS6Vs"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/SZsMmM3e2EU"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/yRXkF-4DZ3I"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/8L6nBsKIkfU"],
    Claudio: ["https://www.youtube.com/embed/5t5nckMW-y0"],
    Clive: ["https://www.youtube.com/embed/H4Gu8H9AL7o"],
    Devil: ["https://www.youtube.com/embed/A51LH6BRG1o"],
    Dragunov: ["https://www.youtube.com/embed/-VK_qiDdk84"],
    Eddy: ["https://www.youtube.com/embed/kjF38-GjCa8"],
    Fahkumram:["https://www.youtube.com/embed/uBayMaQofik"],
    Feng: ["https://www.youtube.com/embed/ZOJ8fu_tJeM"],
    Heihachi: ["https://www.youtube.com/embed/Ro-LbOHsgpw"],
    Hwoarang: ["https://www.youtube.com/embed/Pao-z55EWuE"],
    Jack: ["https://www.youtube.com/embed/9ABkYPqKkq0"],
    Jin: ["https://www.youtube.com/embed/DizsmslsTU4"],
    Jun: ["https://www.youtube.com/embed/OQNohpTtZyM"],
    Kazuya: ["https://www.youtube.com/embed/6yzegvP_ClQ"],
    King: ["https://www.youtube.com/embed/e92Q_O0l7tk"],
    Kuma: ["https://www.youtube.com/embed/DoVMfRbarZE"],
    Lars: ["https://www.youtube.com/embed/sP20NMwxD9Q"],
    Law: ["https://www.youtube.com/embed/UcAEEJ-trKg"],
    Lee: ["https://www.youtube.com/embed/ISpLais1f28"],
    Leo: ["https://www.youtube.com/embed/Ljmx5JpSPe0"],
    Leroy: ["https://www.youtube.com/embed/UhR41T94vp0"],
    Lidia: ["https://www.youtube.com/embed/BFraTYqzSFg"],
    Lili: ["https://www.youtube.com/embed/K5Ikg9zdbKM"],
    Nina: ["https://www.youtube.com/embed/eo8hn-C5oGk"],
    Panda: ["https://www.youtube.com/embed/xptlM3wNtgA"],
    Paul: ["https://www.youtube.com/embed/ujtdTwR6Axo"],
    Raven: ["https://www.youtube.com/embed/OXHcCcgqmro"],
    Reina: ["https://www.youtube.com/embed/QQ9uEcazyQk"],
    Shaheen: ["https://www.youtube.com/embed/R7E6cY0Q4Lk"],
    Steve: ["https://www.youtube.com/embed/tnJz-Likl-M"],
    Victor: ["https://www.youtube.com/embed/oBjv_oL68VU"],
    Xiaoyu: ["https://www.youtube.com/embed/g_8Y5BmM3TI"],
    Yoshimitsu: ["https://www.youtube.com/embed/tqwNO8ZsalE"],
    Zafina: ["https://www.youtube.com/embed/rEQ4Gnf8Hfo"],
  },
  Anna: {
    Alisa: ["https://www.youtube.com/embed/vL8K4zJS6Vs"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/7r5WtMHzR-8"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/0-DyDk2XId0"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/OGGVblmPPWo"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/9M_nlQVY9Bg"],
    Claudio: ["https://www.youtube.com/embed/Xr01KC4jbX8"],
    Clive: ["https://www.youtube.com/embed/YO0gO17deLU"],
    Devil: ["https://www.youtube.com/embed/xCVNUEF6tpI"],
    Dragunov: ["https://www.youtube.com/embed/OZdHBu0o_vg"],
    Eddy: ["https://www.youtube.com/embed/OXcR68pNf8c"],
    Fahkumram:["https://www.youtube.com/embed/5jH6UjwzyPY"],
    Feng: ["https://www.youtube.com/embed/i9IwGmeTUwI"],
    Heihachi: ["https://www.youtube.com/embed/4ji2mUrXFow"],
    Hwoarang: ["https://www.youtube.com/embed/QUCgR8a6tYo"],
    Jack: ["https://www.youtube.com/embed/_9tfDMwVDdk"],
    Jin: ["https://www.youtube.com/embed/DuAnniyMS54"],
    Jun: ["https://www.youtube.com/embed/IHPAkIE3NgE"],
    Kazuya: ["https://www.youtube.com/embed/pErEibFvD9M"],
    King: ["https://www.youtube.com/embed/pByVkb_h6xw"],
    Kuma: ["https://www.youtube.com/embed/hQFXaFo5SLQ"],
    Lars: ["https://www.youtube.com/embed/x4EnUZvq6dM"],
    Law: ["https://www.youtube.com/embed/UP96gKHUUpg"],
    Lee: ["https://www.youtube.com/embed/DbbLFTxF--8"],
    Leo: ["https://www.youtube.com/embed/ByCgQFFYUVo"],
    Leroy: ["https://www.youtube.com/embed/FuDQ5OaHAVA"],
    Lidia: ["https://www.youtube.com/embed/DXJ1C-jY_LU"],
    Lili: ["https://www.youtube.com/embed/3VZXB0VTSmA"],
    Nina: ["https://www.youtube.com/embed/nMhMnlriha0"],
    Panda: ["https://www.youtube.com/embed/NDke4TqiUEA"],
    Paul: ["https://www.youtube.com/embed/SIGh-AO10sY"],
    Raven: ["https://www.youtube.com/embed/89nrEsGZ_HA"],
    Reina: ["https://www.youtube.com/embed/T__scyDvTrU"],
    Shaheen: ["https://www.youtube.com/embed/yFOCxnzpCMY"],
    Steve: ["https://www.youtube.com/embed/KyHJxAr0JfQ"],
    Victor: ["https://www.youtube.com/embed/32c3GVtwSEM"],
    Xiaoyu: ["https://www.youtube.com/embed/bUhXhbCJNeE"],
    Yoshimitsu: ["https://www.youtube.com/embed/A7ZwKUXdiBc"],
    Zafina: ["https://www.youtube.com/embed/ebrH4Pj0F6Y"],
  },
  Armour: {
    Alisa: [],
    Anna: [],
    Armour: [],
    Asuka: [],
    Azucena: [],
    Bryan: [],
    Claudio: [],
    Clive: [],
    Devil: [],
    Dragunov: [],
    Eddy: [],
    Fahkumram: [],
    Feng: [],
    Heihachi: [],
    Hwoarang: [],
    Jack: [],
    Jin: [],
    Jun: [],
    Kazuya: [],
    King: [],
    Kuma: [],
    Lars: [],
    Law: [],
    Lee: [],
    Leo: [],
    Leroy: [],
    Lidia: [],
    Lili: [],
    Nina: [],
    Panda: [],
    Paul: [],
    Raven: [],
    Reina: [],
    Shaheen: [],
    Steve: [],
    Victor: [],
    Xiaoyu: [],
    Yoshimitsu: [],
    Zafina: [],
  },  
  Asuka: {
    Alisa: ["https://www.youtube.com/embed/SZsMmM3e2EU"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/0-DyDk2XId0"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/c1aoqEhwWCY"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/OE4p-1Ni-28"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/JzehgjNOFZQ"],
    Claudio: ["https://www.youtube.com/embed/T2riFhiqrqY"],
    Clive: ["https://www.youtube.com/embed/K1VYTjp3inQ"],
    Devil: ["https://www.youtube.com/embed/LkPVdSEKwHQ"],
    Dragunov: ["https://www.youtube.com/embed/U1_T1eJY96w"],
    Eddy: ["https://www.youtube.com/embed/u7fwuShXRu4"],
    Fahkumram:["https://www.youtube.com/embed/4eiRJ8JO-jw"],
    Feng: ["https://www.youtube.com/embed/XYZc6VraiCY"],
    Heihachi: ["https://www.youtube.com/embed/dLyJS1OaD34"],
    Hwoarang: ["https://www.youtube.com/embed/UiOnHtKPhtU"],
    Jack: ["https://www.youtube.com/embed/DhOr-DlvI5M"],
    Jin: ["https://www.youtube.com/embed/K27SZWgiLec"],
    Jun: ["https://www.youtube.com/embed/VP1C4viagx8"],
    Kazuya: ["https://www.youtube.com/embed/KwoKhDqj9oE"],
    King: ["https://www.youtube.com/embed/9vfwyqxI5Cc"],
    Kuma: ["https://www.youtube.com/embed/NEt-MR0nuKw"],
    Lars: ["https://www.youtube.com/embed/jzX2kTZnHGE"],
    Law: ["https://www.youtube.com/embed/eUgB0fiCnbw"],
    Lee: ["https://www.youtube.com/embed/KkB7IwtAmqY"],
    Leo: ["https://www.youtube.com/embed/1NBQX-cbe6I"],
    Leroy: ["https://www.youtube.com/embed/TM5d6n6V4bs"],
    Lidia: ["https://www.youtube.com/embed/0gEGFv1Dkn8"],
    Lili: ["https://www.youtube.com/embed/TsBw5igzSHE"],
    Nina: ["https://www.youtube.com/embed/tiXakl6znzI"],
    Panda: ["https://www.youtube.com/embed/WNGO9b32Xc4"],
    Paul: ["https://www.youtube.com/embed/SAUD4pwUahA"],
    Raven: ["https://www.youtube.com/embed/LtOFS194zNo"],
    Reina: ["https://www.youtube.com/embed/eYX7vd_7D2c"],
    Shaheen: ["https://www.youtube.com/embed/Xgm0XJau8ZU"],
    Steve: ["https://www.youtube.com/embed/lSjesRz-ej8"],
    Victor: ["https://www.youtube.com/embed/HUEI92iL8Pw"],
    Xiaoyu: ["https://www.youtube.com/embed/K-klmyOxGos"],
    Yoshimitsu: ["https://www.youtube.com/embed/Holhii16f44"],
    Zafina: ["https://www.youtube.com/embed/sqmMfPD6WMM"],
  },
  Azucena: {
    Alisa: ["https://www.youtube.com/embed/yRXkF-4DZ3I"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/OGGVblmPPWo"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/OE4p-1Ni-28"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/nM4Br6in8ek"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/MIKJrCnh-CY"],
    Claudio: ["https://www.youtube.com/embed/vAaRNPSuGYo"],
    Clive: ["https://www.youtube.com/embed/Ud-kC9-1s6c"],
    Devil: ["https://www.youtube.com/embed/3XxgP9ZEQbc"],
    Dragunov: ["https://www.youtube.com/embed/ea9O9frNCHA"],
    Eddy: ["https://www.youtube.com/embed/8UP3LcLEQdU"],
    Fahkumram:["https://www.youtube.com/embed/4mEOBXGzaE4"],
    Feng: ["https://www.youtube.com/embed/oCvPOvs0AmM"],
    Heihachi: ["https://www.youtube.com/embed/i5TY_wzID5Q"],
    Hwoarang: ["https://www.youtube.com/embed/j94fcbrqQCI"],
    Jack: ["https://www.youtube.com/embed/MKV5d8AsXAs"],
    Jin: ["https://www.youtube.com/embed/YxG9cXPNPS8"],
    Jun: ["https://www.youtube.com/embed/jUq3ZXklfrw"],
    Kazuya: [`https://www.youtube.com/embed/S0v3djPH7M0`],
    King: ["https://www.youtube.com/embed/eLNt9G7pqNQ"],
    Kuma: ["https://www.youtube.com/embed/SalYmTWefxs"],
    Lars: ["https://www.youtube.com/embed/-Ys04NLqHwc"],
    Law: ["https://www.youtube.com/embed/4duUAnejKKI"],
    Lee: ["https://www.youtube.com/embed/taxA0F0X8Lc"],
    Leo: ["https://www.youtube.com/embed/JW1sGp38dzc"],
    Leroy: ["https://www.youtube.com/embed/yb9VtUO2Gvw"],
    Lidia: ["https://www.youtube.com/embed/d7hm0q_cn2A"],
    Lili: ["https://www.youtube.com/embed/5_1ZB8xtWYM"],
    Nina: ["https://www.youtube.com/embed/yF-sNnGG6i4"],
    Panda: ["https://www.youtube.com/embed/dxScAYrRQ5k"],
    Paul: ["https://www.youtube.com/embed/U1ERpZrb6BQ"],
    Raven: ["https://www.youtube.com/embed/9DMhy0rkrcs"],
    Reina: ["https://www.youtube.com/embed/sOs-rLWl6r8"],
    Shaheen: ["https://www.youtube.com/embed/nnLld581f04"],
    Steve: ["https://www.youtube.com/embed/Xy6SLAsHew4"],
    Victor: ["https://www.youtube.com/embed/cZyx5JWPRlQ"],
    Xiaoyu: ["https://www.youtube.com/embed/KOVwxOqRt30"],
    Yoshimitsu: ["https://www.youtube.com/embed/X3U1ECIxud8"],
    Zafina: ["https://www.youtube.com/embed/MSrbzLMUhzQ"],
  },
  Bryan: {
    Alisa: ["https://www.youtube.com/embed/8L6nBsKIkfU" ], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/9M_nlQVY9Bg"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/JzehgjNOFZQ"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/MIKJrCnh-CY"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/fRP6S0ywf7A"],
    Claudio: ["https://www.youtube.com/embed/eFLDGP_lSuY"],
    Clive: ["https://www.youtube.com/embed/78T_ZOTeBcM"],
    Devil: ["https://www.youtube.com/embed/SwaiSShvafU"],
    Dragunov: ["https://www.youtube.com/embed/h2ymx7vCtSQ"],
    Eddy: ["https://www.youtube.com/embed/s4AwyvEagwk"],
    Fahkumram:["https://www.youtube.com/embed/JVU487fRY7k"],
    Feng: ["https://www.youtube.com/embed/Fh-6DUg5VqY"],
    Heihachi: ["https://www.youtube.com/embed/MwejAEJHYXo"],
    Hwoarang: ["https://www.youtube.com/embed/3RwTfLFRu_M"],
    Jack: ["https://www.youtube.com/embed/OcnTLv3F0dg"],
    Jin: ["https://www.youtube.com/embed/n2XRQpCNV5E"],
    Jun: ["https://www.youtube.com/embed/UxXu8JaggVk"],
    Kazuya: ["https://www.youtube.com/embed/9dXtGBCbEYc"],
    King: ["https://www.youtube.com/embed/UO6NJdMvXeE"],
    Kuma: ["https://www.youtube.com/embed/IXfl2Gx5k_4"],
    Lars: ["https://www.youtube.com/embed/NIWRMvdp6-4"],
    Law: ["https://www.youtube.com/embed/dMKPWlSxoh8"],
    Lee: ["https://www.youtube.com/embed/yXIHycRrqmQ"],
    Leo: ["https://www.youtube.com/embed/KfRKtn8QRAo"],
    Leroy: ["https://www.youtube.com/embed/43qrOAtx2u4"],
    Lidia: ["https://www.youtube.com/embed/GFI35uHOsww"],
    Lili: ["https://www.youtube.com/embed/LoFlPI78Lrg"],
    Nina: ["https://www.youtube.com/embed/26P3_zi3uIU"],
    Panda: ["https://www.youtube.com/embed/9S_HgpEHwCM"],
    Paul: ["https://www.youtube.com/embed/v8wSSJ_iQmU"],
    Raven: ["https://www.youtube.com/embed/vHbKq_xkuVM"],
    Reina: ["https://www.youtube.com/embed/DtVUoO3kR5U"],
    Shaheen: ["https://www.youtube.com/embed/3IxZdjDwoxQ"],
    Steve: ["https://www.youtube.com/embed/ACcwhqbIfv4"],
    Victor: ["https://www.youtube.com/embed/g4Sa1CdgHWM"],
    Xiaoyu: ["https://www.youtube.com/embed/iarFb5waUy4"],
    Yoshimitsu: ["https://www.youtube.com/embed/kzbocP-KK6A"],
    Zafina: ["https://www.youtube.com/embed/3O1iukSaWSU"],
  },
  Claudio: {
    Alisa: ["https://www.youtube.com/embed/5t5nckMW-y0"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/Xr01KC4jbX8"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/T2riFhiqrqY"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/vAaRNPSuGYo"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/eFLDGP_lSuY"],
    Claudio: ["https://www.youtube.com/embed/4Lxt76IgG2Q"],
    Clive: ["https://www.youtube.com/embed/GnGgdmShCiY"],
    Devil: ["https://www.youtube.com/embed/eBPpShDFr_0"],
    Dragunov: ["https://www.youtube.com/embed/SDQETPAT2B8"],
    Eddy: ["https://www.youtube.com/embed/IJ12wyGMWbM"],
    Fahkumram:["https://www.youtube.com/embed/wueEADX8f5A"],
    Feng: ["https://www.youtube.com/embed/ZesOgXTqDOA"],
    Heihachi: ["https://www.youtube.com/embed/WoYISBa8JDI"],
    Hwoarang: ["https://www.youtube.com/embed/Hn_jGWh5iIY"],
    Jack: ["https://www.youtube.com/embed/nrd6v6dvwWs"],
    Jin: ["https://www.youtube.com/embed/t4IE78SJTJY"],
    Jun: ["https://www.youtube.com/embed/QBUwEQw3kWE"],
    Kazuya: ["https://www.youtube.com/embed/Pb9CLJuT5UI"],
    King: ["https://www.youtube.com/embed/cZFYOJn24CI"],
    Kuma: ["https://www.youtube.com/embed/VibWC9afReA"],
    Lars: ["https://www.youtube.com/embed/6eiNb8Ou_h4"],
    Law: ["https://www.youtube.com/embed/auVwyNOdyXc"],
    Lee: ["https://www.youtube.com/embed/BGWgsH0_ucA"],
    Leo: ["https://www.youtube.com/embed/Eoj2Nn2JkgA"],
    Leroy: ["https://www.youtube.com/embed/hCelXuKJFi0"],
    Lidia: ["https://www.youtube.com/embed/aUF6UKZ-y80"],
    Lili: ["https://www.youtube.com/embed/KMKSIxrzRzE"],
    Nina: ["https://www.youtube.com/embed/FOS3_qTRMfA"],
    Panda: ["https://www.youtube.com/embed/vhKySRczay0"],
    Paul: ["https://www.youtube.com/embed/Q1MHIsGOhGM"],
    Raven: ["https://www.youtube.com/embed/XW4H0JGLevY"],
    Reina: ["https://www.youtube.com/embed/jQ6ZtTx373A"],
    Shaheen: ["https://www.youtube.com/embed/W9d-Yoe_P-Q"],
    Steve: ["https://www.youtube.com/embed/93GpW0X-T4g"],
    Victor: ["https://www.youtube.com/embed/JaVnSh43sNo"],
    Xiaoyu: ["https://www.youtube.com/embed/F16D0a0acUc"],
    Yoshimitsu: ["https://www.youtube.com/embed/in-t33vibp8"],
    Zafina: [],
  },
  Clive: {
    Alisa: ["https://www.youtube.com/embed/H4Gu8H9AL7o"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/YO0gO17deLU"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/K1VYTjp3inQ"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/Ud-kC9-1s6c"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/78T_ZOTeBcM"],
    Claudio: ["https://www.youtube.com/embed/GnGgdmShCiY"],
    Clive: ["https://www.youtube.com/embed/80Y-p4AoPvU"],
    Devil: ["https://www.youtube.com/embed/_7TkVUi-qn0"],
    Dragunov: ["https://www.youtube.com/embed/PjqNXqZA604"],
    Eddy: ["https://www.youtube.com/embed/zlcYcQAqt6E"],
    Fahkumram:["https://www.youtube.com/embed/aGDb4gy8pUI"],
    Feng: ["https://www.youtube.com/embed/In6SN1Nuj0k"],
    Heihachi: ["https://www.youtube.com/embed/dpFFltV76QA"],
    Hwoarang: ["https://www.youtube.com/embed/GeOtdhWRhoc"],
    Jack: ["https://www.youtube.com/embed/UeY-a2f2XmA"],
    Jin: ["https://www.youtube.com/embed/lqjaEQ4t86I"],
    Jun: ["https://www.youtube.com/embed/dXwn_SHyTfk"],
    Kazuya: ["https://www.youtube.com/embed/5ru75HIFh_Q"],
    King: ["https://www.youtube.com/embed/0fDg5e3biu4"],
    Kuma: ["https://www.youtube.com/embed/D-uKbELuJHQ"],
    Lars: ["https://www.youtube.com/embed/uDntqPD1UWA"],
    Law: ["https://www.youtube.com/embed/P2682s36NVc"],
    Lee: ["https://www.youtube.com/embed/iZQotPvEcN4"],
    Leo: ["https://www.youtube.com/embed/UOtRbsF5tsk"],
    Leroy: ["https://www.youtube.com/embed/ulA-e4XEr_s"],
    Lidia: ["https://www.youtube.com/embed/N0PUTsPHK7o"],
    Lili: ["https://www.youtube.com/embed/iFngzx3RiGY"],
    Nina: ["https://www.youtube.com/embed/D2VS1kTotS0"],
    Panda: ["https://www.youtube.com/embed/IjqzYHUFXFc"],
    Paul: ["https://www.youtube.com/embed/WCK8SA5zh30"],
    Raven: ["https://www.youtube.com/embed/AX_Ie7PKrYk"],
    Reina: ["https://www.youtube.com/embed/aN2B0qBjvpI"],
    Shaheen: ["https://www.youtube.com/embed/Poy83jzMGZw"],
    Steve: ["https://www.youtube.com/embed/t77hdliFtAk"],
    Victor: ["https://www.youtube.com/embed/NRazal7mLog"],
    Xiaoyu: ["https://www.youtube.com/embed/xeju4jqq9uc"],
    Yoshimitsu: ["https://www.youtube.com/embed/gUczI_sxqEc"],
    Zafina: ["https://www.youtube.com/embed/KpzTubVfKS4"],
  },
  Devil: {
    Alisa: ["https://www.youtube.com/embed/A51LH6BRG1o"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/xCVNUEF6tpI"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/LkPVdSEKwHQ"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/3XxgP9ZEQbc"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/SwaiSShvafU"],
    Claudio: ["https://www.youtube.com/embed/eBPpShDFr_0"],
    Clive: ["https://www.youtube.com/embed/_7TkVUi-qn0"],
    Devil: ["https://www.youtube.com/embed/NEVfSbC9wIo"],
    Dragunov: ["https://www.youtube.com/embed/Lxfo2ilYCMg"],
    Eddy: ["https://www.youtube.com/embed/_Me2vPqkFXA"],
    Fahkumram:["https://www.youtube.com/embed/0yDPQnpm48c"],
    Feng: ["https://www.youtube.com/embed/LrTUw-3_Ni0"],
    Heihachi: ["https://www.youtube.com/embed/gWd0rff8NSw"],
    Hwoarang: ["https://www.youtube.com/embed/0vYOVdpWq9E"],
    Jack: ["https://www.youtube.com/embed/i2UTbOhXh9M"],
    Jin: ["https://www.youtube.com/embed/5tiIRAzsBXs"],
    Jun: ["https://www.youtube.com/embed/wNsLssI_lIw"],
    Kazuya: ["https://www.youtube.com/embed/_n1GyJiL43o"],
    King: ["https://www.youtube.com/embed/2DiqKplwtjI"],
    Kuma: ["https://www.youtube.com/embed/wuoxjQFgqXk"],
    Lars: ["https://www.youtube.com/embed/UBFShZSXrg0"],
    Law: ["https://www.youtube.com/embed/cHywJu9eKfo"],
    Lee: ["https://www.youtube.com/embed/SeGqSsyFd1k"],
    Leo: ["https://www.youtube.com/embed/kSfdAAm5O2A"],
    Leroy: ["https://www.youtube.com/embed/8fawaWcyVoM"],
    Lidia: ["https://www.youtube.com/embed/SUjfXyUp3uI"],
    Lili: ["https://www.youtube.com/embed/cVsW7aLjRHQ"],
    Nina: ["https://www.youtube.com/embed/5ssyDi1AKAI"],
    Panda: ["https://www.youtube.com/embed/gyAAKCOyrm8"],
    Paul: ["https://www.youtube.com/embed/He8n1tOqIEU"],
    Raven: ["https://www.youtube.com/embed/KW6ecZx_qDU"],
    Reina: ["https://www.youtube.com/embed/K4xhIpUfsy8"],
    Shaheen: ["https://www.youtube.com/embed/cl2hfVyNMUw"],
    Steve: ["https://www.youtube.com/embed/LQioKg1qKfk"],
    Victor: ["https://www.youtube.com/embed/atzR3MKUrMo"],
    Xiaoyu: ["https://www.youtube.com/embed/SgQkiAemiMo"],
    Yoshimitsu: ["https://www.youtube.com/embed/ix-Rmq-3Vsk"],
    Zafina: ["https://www.youtube.com/embed/0d1BtDOsNgk"],
  },
  Dragunov: {
    Alisa: ["https://www.youtube.com/embed/-VK_qiDdk84"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/OZdHBu0o_vg"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/U1_T1eJY96w"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/ea9O9frNCHA"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/h2ymx7vCtSQ"],
    Claudio: ["https://www.youtube.com/embed/SDQETPAT2B8"],
    Clive: ["https://www.youtube.com/embed/PjqNXqZA604"],
    Devil: ["https://www.youtube.com/embed/Lxfo2ilYCMg"],
    Dragunov: ["https://www.youtube.com/embed/9J1Z99mF5Y0"],
    Eddy: ["https://www.youtube.com/embed/15__ZRtBoxA"],
    Fahkumram:["https://www.youtube.com/embed/4j3CX1dcle0"],
    Feng: ["https://www.youtube.com/embed/zrhHIWtXbHM"],
    Heihachi: ["https://www.youtube.com/embed/VfhcquEjZ00"],
    Hwoarang: ["https://www.youtube.com/embed/JvVVMB1VLQ4"],
    Jack: ["https://www.youtube.com/embed/ytoruJhDXlM"],
    Jin: ["https://www.youtube.com/embed/XB31ikjAmIk"],
    Jun: ["https://www.youtube.com/embed/yFya0snsiKU"],
    Kazuya: ["https://www.youtube.com/embed/eOOuvodACf0"],
    King: ["https://www.youtube.com/embed/4yKorDwA3b8"],
    Kuma: ["https://www.youtube.com/embed/T4TegaoNKd8"],
    Lars: ["https://www.youtube.com/embed/B38yY_CN2gc"],
    Law: ["https://www.youtube.com/embed/_CWzUMLFkAc"],
    Lee: ["https://www.youtube.com/embed/NnaVfl5kTZw"],
    Leo: ["https://www.youtube.com/embed/ZRnuQGaInGM"],
    Leroy: ["https://www.youtube.com/embed/3T3BfAq0DpU"],
    Lidia: ["https://www.youtube.com/embed/YMkzGgYRyYE"],
    Lili: ["https://www.youtube.com/embed/roajOB02Wvk"],
    Nina: ["https://www.youtube.com/embed/BvHtH7GKPhQ"],
    Panda: ["https://www.youtube.com/embed/9R1TUAXROEo"],
    Paul: ["https://www.youtube.com/embed/AFV_YwLOzJ0"],
    Raven: ["https://www.youtube.com/embed/7CHxzcQaebI"],
    Reina: ["https://www.youtube.com/embed/c7eoMXwoehs"],
    Shaheen: ["https://www.youtube.com/embed/sJUL1-tfGDk"],
    Steve: ["https://www.youtube.com/embed/cl4cRi-53B8"],
    Victor: ["https://www.youtube.com/embed/RVsslHDTrLY"],
    Xiaoyu: ["https://www.youtube.com/embed/CMoM_6T2WUE"],
    Yoshimitsu: ["https://www.youtube.com/embed/AkMPpx_SdBA"],
    Zafina: ["https://www.youtube.com/embed/IpBcfZ87vqM"],
  },
  Eddy: {
    Alisa: ["https://www.youtube.com/embed/kjF38-GjCa8"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/OXcR68pNf8c"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/u7fwuShXRu4"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/8UP3LcLEQdU"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/s4AwyvEagwk"],
    Claudio: ["https://www.youtube.com/embed/IJ12wyGMWbM"],
    Clive: ["https://www.youtube.com/embed/zlcYcQAqt6E"],
    Devil: ["https://www.youtube.com/embed/_Me2vPqkFXA"],
    Dragunov: ["https://www.youtube.com/embed/15__ZRtBoxA"],
    Eddy: ["https://www.youtube.com/embed/LJR-JK13x9A"],
    Fahkumram:["https://www.youtube.com/embed/UpF8owBeahY"],
    Feng: ["https://www.youtube.com/embed/aVyBK-jIadA"],
    Heihachi: ["https://www.youtube.com/embed/oG_ynupDpqk"],
    Hwoarang: ["https://www.youtube.com/embed/zkvQWNTDxoo"],
    Jack: ["https://www.youtube.com/embed/sx2cYMZB4Dg"],
    Jin: ["https://www.youtube.com/embed/_czdLnSxji4"],
    Jun: ["https://www.youtube.com/embed/tzSHxwhGgRc"],
    Kazuya: ["https://www.youtube.com/embed/4yCEvDHkjKs"],
    King: ["https://www.youtube.com/embed/3e2wJLQkxMw"],
    Kuma: ["https://www.youtube.com/embed/XyAGC6A4jRo"],
    Lars: ["https://www.youtube.com/embed/vM2tJ80slNU"],
    Law: ["https://www.youtube.com/embed/ZbI4W_VaQ2Y"],
    Lee: ["https://www.youtube.com/embed/IigpfkgLXF8"],
    Leo: ["https://www.youtube.com/embed/wH4sPAtS0KY"],
    Leroy: ["https://www.youtube.com/embed/3adYTII2i7M"],
    Lidia: ["https://www.youtube.com/embed/gs0mYxJkKa8"],
    Lili: ["https://www.youtube.com/embed/X68ofpABqJE"],
    Nina: ["https://www.youtube.com/embed/CHRtZ3IOkT0"],
    Panda: ["https://www.youtube.com/embed/-Go6KkzshPI"],
    Paul: ["https://www.youtube.com/embed/9uYESKCFKtQ"],
    Raven: ["https://www.youtube.com/embed/LFgJaCSlNTs"],
    Reina: ["https://www.youtube.com/embed/mMvm-Efl9iw"],
    Shaheen: ["https://www.youtube.com/embed/cmrU6NaKJNo"],
    Steve: ["https://www.youtube.com/embed/UXIF11sT8mo"],
    Victor: ["https://www.youtube.com/embed/wxokvJj7ghw"],
    Xiaoyu: ["https://www.youtube.com/embed/L-syT6BJ2dc"],
    Yoshimitsu: ["https://www.youtube.com/embed/YiNYHv8_6ok"],
    Zafina: ["https://www.youtube.com/embed/BJTAItSWk5I"],
  },
  Fahkumram: {
    Alisa: ["https://www.youtube.com/embed/uBayMaQofik"],
    Anna: ["https://www.youtube.com/embed/5jH6UjwzyPY"],
    Armour: [],
    Asuka: ["https://www.youtube.com/embed/4eiRJ8JO-jw"],
    Azucena: ["https://www.youtube.com/embed/4mEOBXGzaE4"],
    Bryan: ["https://www.youtube.com/embed/JVU487fRY7k"],
    Claudio: ["https://www.youtube.com/embed/wueEADX8f5A"],
    Clive: ["https://www.youtube.com/embed/aGDb4gy8pUI"],
    Devil: ["https://www.youtube.com/embed/0yDPQnpm48c"],
    Dragunov: ["https://www.youtube.com/embed/4j3CX1dcle0"],
    Eddy: ["https://www.youtube.com/embed/UpF8owBeahY"],
    Fahkumram: ["https://www.youtube.com/embed/JJH5VJjoi8A"],
    Feng: ["https://www.youtube.com/embed/IrTq1u-YEPU"],
    Heihachi: ["https://www.youtube.com/embed/xmcMBnaimuY"],
    Hwoarang: ["https://www.youtube.com/embed/sshyqB4cPJ4"],
    Jack: ["https://www.youtube.com/embed/QWvMIgAihLE"],
    Jin: ["https://www.youtube.com/embed/H8DuKyIhoEA"],
    Jun: ["https://www.youtube.com/embed/70kslDSPaGU"],
    Kazuya: ["https://www.youtube.com/embed/MdZEqZE0u4M"],
    King: ["https://www.youtube.com/embed/ADfLMVed83o"],
    Kuma: [],
    Lars: ["https://www.youtube.com/embed/B_lN9-oyrM4"],
    Law: ["https://www.youtube.com/embed/W2eA6mArlaM"],
    Lee: ["https://www.youtube.com/embed/4Y768Fx8juw"],
    Leo: ["https://www.youtube.com/embed/z4MPNUTTxEs"],
    Leroy: ["https://www.youtube.com/embed/6hmQl5W29i8"],
    Lidia: ["https://www.youtube.com/embed/cDptee2kMBE"],
    Lili: ["https://www.youtube.com/embed/5qUtDa5xbfc"],
    Nina: ["https://www.youtube.com/embed/eHgcUxtw-3U"],
    Panda: ["https://www.youtube.com/embed/hhx_IMA3Owg"],
    Paul: ["https://www.youtube.com/embed/akX69ULr60w"],
    Raven: ["https://www.youtube.com/embed/ym_LngGoYzw"],
    Reina: ["https://www.youtube.com/embed/y5yfw64ipUI"],
    Shaheen: [],
    Steve: ["https://www.youtube.com/embed/fIowSOx172E"],
    Victor: ["https://www.youtube.com/embed/Tp2kzT_ZzmM"],
    Xiaoyu: ["https://www.youtube.com/embed/gtkNuxBEWMg"],
    Yoshimitsu: ["https://www.youtube.com/embed/O5zWVvhty3Y"],
    Zafina: ["https://www.youtube.com/embed/cLetl1KhlJQ"],
  },
  Feng: {
    Alisa: ["https://www.youtube.com/embed/ZOJ8fu_tJeM"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/i9IwGmeTUwI"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/XYZc6VraiCY"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/oCvPOvs0AmM"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/Fh-6DUg5VqY"],
    Claudio: ["https://www.youtube.com/embed/ZesOgXTqDOA"],
    Clive: ["https://www.youtube.com/embed/In6SN1Nuj0k"],
    Devil: ["https://www.youtube.com/embed/LrTUw-3_Ni0"],
    Dragunov: ["https://www.youtube.com/embed/zrhHIWtXbHM"],
    Eddy: ["https://www.youtube.com/embed/aVyBK-jIadA"],
    Fahkumram:["https://www.youtube.com/embed/IrTq1u-YEPU"],
    Feng: ["https://www.youtube.com/embed/V5x3VbgJIzk"],
    Heihachi: ["https://www.youtube.com/embed/qxduWO7aVAk"],
    Hwoarang: ["https://www.youtube.com/embed/Lq7qs9p-E1c"],
    Jack: ["https://www.youtube.com/embed/zfpqqZ9zrIo"],
    Jin: ["https://www.youtube.com/embed/rCwdIgnXg08"],
    Jun: ["https://www.youtube.com/embed/gWulpF_83ZY"],
    Kazuya: ["https://www.youtube.com/embed/R7WIdkDM3aM"],
    King: ["https://www.youtube.com/embed/QSg-4Q0mebA"],
    Kuma: ["https://www.youtube.com/embed/SbQv0ke6FMg"],
    Lars: ["https://www.youtube.com/embed/G8N1ZmFW4vo"],
    Law: ["https://www.youtube.com/embed/SbPtJGZD3Ns"],
    Lee: ["https://www.youtube.com/embed/E0bNLZvtkwU"],
    Leo: ["https://www.youtube.com/embed/PL2_7R_RFW8"],
    Leroy: ["https://www.youtube.com/embed/vn7NjzRMZo4"],
    Lidia: ["https://www.youtube.com/embed/o5lnns2v9XM"],
    Lili: ["https://www.youtube.com/embed/XkS4qPZumpc"],
    Nina: ["https://www.youtube.com/embed/0oVckKCkZFE"],
    Panda: ["https://www.youtube.com/embed/LcIEpWTU76c"],
    Paul: ["https://www.youtube.com/embed/C-9SseDU3tU"],
    Raven: ["https://www.youtube.com/embed/vvBRz4nrEbk"],
    Reina: ["https://www.youtube.com/embed/D1EqdfTRpZU"],
    Shaheen: ["https://www.youtube.com/embed/WN8gpBEZNic"],
    Steve: ["https://www.youtube.com/embed/WkNiPmOIWEQ"],
    Victor: ["https://www.youtube.com/embed/nKX562ofIGU"],
    Xiaoyu: ["https://www.youtube.com/embed/YI4ypF4N9WQ"],
    Yoshimitsu: ["https://www.youtube.com/embed/fp_DEYSHt-M"],
    Zafina: ["https://www.youtube.com/embed/k21l8kfWwyQ"],
  },
  Heihachi: {
    Alisa: ["https://www.youtube.com/embed/Ro-LbOHsgpw"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/4ji2mUrXFow"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/dLyJS1OaD34"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/i5TY_wzID5Q"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/MwejAEJHYXo"],
    Claudio: ["https://www.youtube.com/embed/WoYISBa8JDI"],
    Clive: ["https://www.youtube.com/embed/dpFFltV76QA"],
    Devil: ["https://www.youtube.com/embed/gWd0rff8NSw"],
    Dragunov: ["https://www.youtube.com/embed/VfhcquEjZ00"],
    Eddy: ["https://www.youtube.com/embed/oG_ynupDpqk"],
    Fahkumram:["https://www.youtube.com/embed/xmcMBnaimuY"],
    Feng: ["https://www.youtube.com/embed/qxduWO7aVAk"],
    Heihachi: ["https://www.youtube.com/embed/2fVrGsOoKPI"],
    Hwoarang: ["https://www.youtube.com/embed/bQo4cxLz31k"],
    Jack: ["https://www.youtube.com/embed/ahh_hZj9-dU"],
    Jin: ["https://www.youtube.com/embed/uKDpZMVocQw"],
    Jun: ["https://www.youtube.com/embed/HTRLxHRMHmo"],
    Kazuya: ["https://www.youtube.com/embed/62oA9gLFef8"],
    King: ["https://www.youtube.com/embed/FFF75G1lt-Y"],
    Kuma: ["https://www.youtube.com/embed/NSMi2NcjgQQ"],
    Lars: ["https://www.youtube.com/embed/fbvinXHTrpc"],
    Law: ["https://www.youtube.com/embed/1-XWqoJdXqY"],
    Lee: ["https://www.youtube.com/embed/8vIm-To8wEM"],
    Leo: ["https://www.youtube.com/embed/Bum_r8G9yjQ"],
    Leroy: ["https://www.youtube.com/embed/g-0iCwzkKbM"],
    Lidia: ["https://www.youtube.com/embed/m_KDVgt3Ulc"],
    Lili: ["https://www.youtube.com/embed/yoT5nXGH08M"],
    Nina: ["https://www.youtube.com/embed/EGC2ZjjbZ30"],
    Panda: ["https://www.youtube.com/embed/93hq0YU3Gqk"],
    Paul: ["https://www.youtube.com/embed/B0Xat6dF-QM"],
    Raven: ["https://www.youtube.com/embed/TNg1J7okZgM"],
    Reina: ["https://www.youtube.com/embed/usLxVbzCYNo"],
    Shaheen: ["https://www.youtube.com/embed/80xUzZ8StDA"],
    Steve: ["https://www.youtube.com/embed/V2rbtPmlJ5A"],
    Victor: ["https://www.youtube.com/embed/5vziUrbD490"],
    Xiaoyu: ["https://www.youtube.com/embed/5Yd98XkZnm4"],
    Yoshimitsu: ["https://www.youtube.com/embed/VZhKPprtL3Y"],
    Zafina: ["https://www.youtube.com/embed/vEqi7Jd_Uxc"],
  },
  Hwoarang: {
    Alisa: ["https://www.youtube.com/embed/Pao-z55EWuE"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/QUCgR8a6tYo"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/UiOnHtKPhtU"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/j94fcbrqQCI"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/3RwTfLFRu_M"],
    Claudio: ["https://www.youtube.com/embed/Hn_jGWh5iIY"],
    Clive: ["https://www.youtube.com/embed/GeOtdhWRhoc"],
    Devil: ["https://www.youtube.com/embed/0vYOVdpWq9E"],
    Dragunov: ["https://www.youtube.com/embed/JvVVMB1VLQ4"],
    Eddy: ["https://www.youtube.com/embed/zkvQWNTDxoo"],
    Fahkumram:["https://www.youtube.com/embed/sshyqB4cPJ4"],
    Feng: ["https://www.youtube.com/embed/Lq7qs9p-E1c"],
    Heihachi: ["https://www.youtube.com/embed/bQo4cxLz31k"],
    Hwoarang: ["https://www.youtube.com/embed/Defzg_v_gI4"],
    Jack: ["https://www.youtube.com/embed/thvMoWjPOeo"],
    Jin: ["https://www.youtube.com/embed/qOuf6cCIAyE"],
    Jun: ["https://www.youtube.com/embed/eTbklXC6s2c"],
    Kazuya: ["https://www.youtube.com/embed/lIe_X-qmk3U"],
    King: ["https://www.youtube.com/embed/LU98uuBtYX0"],
    Kuma: ["https://www.youtube.com/embed/pzXw9V_34j8"],
    Lars: ["https://www.youtube.com/embed/ElkPLEK-MuI"],
    Law: ["https://www.youtube.com/embed/V697wVUr9CI"],
    Lee: ["https://www.youtube.com/embed/SCwtNWr7BZY"],
    Leo: ["https://www.youtube.com/embed/G_lx1th04T8"],
    Leroy: ["https://www.youtube.com/embed/S93G04KUiy4"],
    Lidia: ["https://www.youtube.com/embed/jAAGKivN-BA"],
    Lili: ["https://www.youtube.com/embed/MEIIkcNvTHM"],
    Nina: ["https://www.youtube.com/embed/fxiMTNmHXZE"],
    Panda: ["https://www.youtube.com/embed/YdqST5-1HQ0"],
    Paul: ["https://www.youtube.com/embed/nXb2rEwXz6c"],
    Raven: ["https://www.youtube.com/embed/2Dgecb_Wfjo"],
    Reina: ["https://www.youtube.com/embed/pjD8KJbxcKE"],
    Shaheen: ["https://www.youtube.com/embed/bvjRn2-Vklw"],
    Steve: ["https://www.youtube.com/embed/s30L-GPAZUU"],
    Victor: ["https://www.youtube.com/embed/9Div4NHtv2Q"],
    Xiaoyu: ["https://www.youtube.com/embed/ReQu8jftJIg"],
    Yoshimitsu:["https://www.youtube.com/embed/HF613P8mylQ"],
    Zafina: ["https://www.youtube.com/embed/TYRwY5nJpjY"],
  },
  Jack: {
    Alisa: ["https://www.youtube.com/embed/9ABkYPqKkq0"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/_9tfDMwVDdk"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/DhOr-DlvI5M"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/MKV5d8AsXAs"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/OcnTLv3F0dg"],
    Claudio: ["https://www.youtube.com/embed/nrd6v6dvwWs"],
    Clive: ["https://www.youtube.com/embed/UeY-a2f2XmA"],
    Devil: ["https://www.youtube.com/embed/i2UTbOhXh9M"],
    Dragunov: ["https://www.youtube.com/embed/ytoruJhDXlM"],
    Eddy: ["https://www.youtube.com/embed/sx2cYMZB4Dg"],
    Fahkumram:["https://www.youtube.com/embed/QWvMIgAihLE"],
    Feng: ["https://www.youtube.com/embed/zfpqqZ9zrIo"],
    Heihachi: ["https://www.youtube.com/embed/ahh_hZj9-dU"],
    Hwoarang: ["https://www.youtube.com/embed/thvMoWjPOeo"],
    Jack: ["https://www.youtube.com/embed/grzGXMzG4_Q"],
    Jin: ["https://www.youtube.com/embed/E39ouhc0zDY"],
    Jun: ["https://www.youtube.com/embed/U3BOY6xXp94"],
    Kazuya: ["https://www.youtube.com/embed/WZJ3rO7O0uA"],
    King: ["https://www.youtube.com/embed/TE-je2OzE5s"],
    Kuma: ["https://www.youtube.com/embed/BkJNXGMNuFQ"],
    Lars: ["https://www.youtube.com/embed/MmAvuQFLDOc"],
    Law: ["https://www.youtube.com/embed/736FTLmoPqo"],
    Lee: ["https://www.youtube.com/embed/X-Q5iVvuCW0"],
    Leo: ["https://www.youtube.com/embed/ei1GQjj_x8g"],
    Leroy: ["https://www.youtube.com/embed/4yHOQyRBYiQ"],
    Lidia: ["https://www.youtube.com/embed/1VbHaFANxgQ"],
    Lili: ["https://www.youtube.com/embed/lQQ96NZF0IM"],
    Nina: ["https://www.youtube.com/embed/aQWX2pa8qZY"],
    Panda: ["https://www.youtube.com/embed/Nf7vfOoZOic"],
    Paul: ["https://www.youtube.com/embed/OfQwomhE95E"],
    Raven: ["https://www.youtube.com/embed/y3GWHpbfXfE"],
    Reina: ["https://www.youtube.com/embed/Hp50kY3ZXd0"],
    Shaheen: ["https://www.youtube.com/embed/7tYREaoHtIo"],
    Steve: ["https://www.youtube.com/embed/wemFDYlz1Rc"],
    Victor: ["https://www.youtube.com/embed/K1Hy9olmAiE"],
    Xiaoyu: ["https://www.youtube.com/embed/C-OkV9Im6vk"],
    Yoshimitsu: ["https://www.youtube.com/embed/JAOE3ZHaKu0"],
    Zafina: ["https://www.youtube.com/embed/MciyqEIZQkY"],
  },
  Jin: {
    Alisa: ["https://www.youtube.com/embed/DizsmslsTU4"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/DuAnniyMS54"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/K27SZWgiLec"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/YxG9cXPNPS8"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/n2XRQpCNV5E"],
    Claudio: ["https://www.youtube.com/embed/t4IE78SJTJY"],
    Clive: ["https://www.youtube.com/embed/lqjaEQ4t86I"],
    Devil: ["https://www.youtube.com/embed/5tiIRAzsBXs"],
    Dragunov: ["https://www.youtube.com/embed/XB31ikjAmIk"],
    Eddy: ["https://www.youtube.com/embed/_czdLnSxji4"],
    Fahkumram:["https://www.youtube.com/embed/H8DuKyIhoEA"],
    Feng: ["https://www.youtube.com/embed/rCwdIgnXg08"],
    Heihachi: ["https://www.youtube.com/embed/uKDpZMVocQw"],
    Hwoarang: ["https://www.youtube.com/embed/qOuf6cCIAyE"],
    Jack: ["https://www.youtube.com/embed/E39ouhc0zDY"],
    Jin: ["https://www.youtube.com/embed/A8T3M6dGX2U"],
    Jun: ["https://www.youtube.com/embed/FS2y0CmZ6CY"],
    Kazuya: ["https://www.youtube.com/embed/-wEg76lX3Fw"],
    King: ["https://www.youtube.com/embed/Cvwhk7o-jUU"],
    Kuma: ["https://www.youtube.com/embed/o7uQ27-FCks"],
    Lars: ["https://www.youtube.com/embed/0HdVE6HtAm0"],
    Law: ["https://www.youtube.com/embed/4Av2dIAI_Ac"],
    Lee: ["https://www.youtube.com/embed/Ntk-rzJWxFs"],
    Leo: ["https://www.youtube.com/embed/nVxqHK7RnG4"],
    Leroy: ["https://www.youtube.com/embed/zVkNldSvPlk"],
    Lidia: ["https://www.youtube.com/embed/QTAJ1AfA6RE"],
    Lili: ["https://www.youtube.com/embed/F06Q9sobIK4"],
    Nina: ["https://www.youtube.com/embed/ZqI5UOelaVw"],
    Panda: ["https://www.youtube.com/embed/CnodrWllzO0"],
    Paul: ["https://www.youtube.com/embed/zoPjtmlQjQQ"],
    Raven: ["https://www.youtube.com/embed/lpsiKNbR72U"],
    Reina: ["https://www.youtube.com/embed/SHZQ9wcStAc"],
    Shaheen: ["https://www.youtube.com/embed/US0N87oWCzc"],
    Steve: ["https://www.youtube.com/embed/z82yJxzd4Po"],
    Victor: ["https://www.youtube.com/embed/ng1tIkIJafQ"],
    Xiaoyu: ["https://www.youtube.com/embed/kX59WBCxiUQ"],
    Yoshimitsu: ["https://www.youtube.com/embed/Cr6LZkjhMn4"],
    Zafina: ["https://www.youtube.com/embed/WwUKCOFIe04"],
  },
  Jun: {
    Alisa: ["https://www.youtube.com/embed/OQNohpTtZyM"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/IHPAkIE3NgE"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/VP1C4viagx8"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/jUq3ZXklfrw"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/UxXu8JaggVk"],
    Claudio: ["https://www.youtube.com/embed/QBUwEQw3kWE"],
    Clive: ["https://www.youtube.com/embed/dXwn_SHyTfk"],
    Devil: ["https://www.youtube.com/embed/wNsLssI_lIw"],
    Dragunov: ["https://www.youtube.com/embed/yFya0snsiKU"],
    Eddy: ["https://www.youtube.com/embed/tzSHxwhGgRc"],
    Fahkumram:["https://www.youtube.com/embed/70kslDSPaGU"],
    Feng: ["https://www.youtube.com/embed/gWulpF_83ZY"],
    Heihachi: ["https://www.youtube.com/embed/HTRLxHRMHmo"],
    Hwoarang: ["https://www.youtube.com/embed/eTbklXC6s2c"],
    Jack: ["https://www.youtube.com/embed/U3BOY6xXp94"],
    Jin: ["https://www.youtube.com/embed/FS2y0CmZ6CY"],
    Jun: ["https://www.youtube.com/embed/dot70GtoZNs"],
    Kazuya: ["https://www.youtube.com/embed/Xp9DbP4yuqw"],
    King: ["https://www.youtube.com/embed/efQBgfmEDv0"],
    Kuma: ["https://www.youtube.com/embed/_cWPxsT1SFw"],
    Lars: ["https://www.youtube.com/embed/fa85CXYSE30"],
    Law: ["https://www.youtube.com/embed/KwyzAK08_xY"],
    Lee: ["https://www.youtube.com/embed/MjXx1NXsJ3A"],
    Leo: ["https://www.youtube.com/embed/GLDJ14vGpjA"],
    Leroy: ["https://www.youtube.com/embed/LaSl2lqKgHs"],
    Lidia: ["https://www.youtube.com/embed/NG5nepgT6uI"],
    Lili: ["https://www.youtube.com/embed/eFLk2ydSaS0"],
    Nina: ["https://www.youtube.com/embed/hGQ-0SQDlh0"],
    Panda: ["https://www.youtube.com/embed/EFwePQnvRoM"],
    Paul: ["https://www.youtube.com/embed/ey0iooo5rxk"],
    Raven: ["https://www.youtube.com/embed/onbMCTQFSu8"],
    Reina: ["https://www.youtube.com/embed/lIDh9hkYgbw"],
    Shaheen: ["https://www.youtube.com/embed/eTW2EHlA3WE"],
    Steve: ["https://www.youtube.com/embed/s_C0tuGVBWA"],
    Victor: ["https://www.youtube.com/embed/Q6xTgFPgJkU"],
    Xiaoyu: ["https://www.youtube.com/embed/6blPjp1cDBI"],
    Yoshimitsu: ["https://www.youtube.com/embed/5sMH1nu5Mtc"],
    Zafina: ["https://www.youtube.com/embed/kSy9u1P9onw"],
  },
  Kazuya: {
    Alisa: ["https://www.youtube.com/embed/6yzegvP_ClQ"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/pErEibFvD9M"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/KwoKhDqj9oE"], // Add video links or data here
    Azucena: [`https://www.youtube.com/embed/S0v3djPH7M0`], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/9dXtGBCbEYc"],
    Claudio: ["https://www.youtube.com/embed/Pb9CLJuT5UI"],
    Clive: ["https://www.youtube.com/embed/5ru75HIFh_Q"],
    Devil: ["https://www.youtube.com/embed/_n1GyJiL43o"],
    Dragunov: ["https://www.youtube.com/embed/eOOuvodACf0"],
    Eddy: ["https://www.youtube.com/embed/4yCEvDHkjKs"],
    Fahkumram:["https://www.youtube.com/embed/MdZEqZE0u4M"],
    Feng: ["https://www.youtube.com/embed/R7WIdkDM3aM"],
    Heihachi: ["https://www.youtube.com/embed/62oA9gLFef8"],
    Hwoarang: ["https://www.youtube.com/embed/lIe_X-qmk3U"],
    Jack: ["https://www.youtube.com/embed/WZJ3rO7O0uA"],
    Jin: ["https://www.youtube.com/embed/-wEg76lX3Fw"],
    Jun: ["https://www.youtube.com/embed/Xp9DbP4yuqw"],
    Kazuya: ["https://www.youtube.com/embed/GHlBspPDXX0"],
    King: ["https://www.youtube.com/embed/51CA7SD1pk0"],
    Kuma: ["https://www.youtube.com/embed/2EuTfGzQzQQ"],
    Lars: ["https://www.youtube.com/embed/rZfnao93o_w"],
    Law: ["https://www.youtube.com/embed/ebH1WOlX3mQ"],
    Lee: ["https://www.youtube.com/embed/plVGmLVsS-I"],
    Leo: ["https://www.youtube.com/embed/Ng5h9vvif0A"],
    Leroy: ["https://www.youtube.com/embed/HKPeQuFKoGI"],
    Lidia: ["https://www.youtube.com/embed/sCioC-gqG3A"],
    Lili: ["https://www.youtube.com/embed/9gJzSAvJ__E"],
    Nina: ["https://www.youtube.com/embed/CIT30BaKajw"],
    Panda: ["https://www.youtube.com/embed/iqlVhvGK0iE"],
    Paul: ["https://www.youtube.com/embed/gOo77gBorGE"],
    Raven: ["https://www.youtube.com/embed/gZv9HDIF8Sc"],
    Reina: ["https://www.youtube.com/embed/VYGyeLBkYR8"],
    Shaheen: ["https://www.youtube.com/embed/HxM_WEJM3AY"],
    Steve: ["https://www.youtube.com/embed/XFKMr38Ej8c"],
    Victor: ["https://www.youtube.com/embed/xFkCpVkabW4"],
    Xiaoyu: ["https://www.youtube.com/embed/5R3R9zVHyLE"],
    Yoshimitsu: ["https://www.youtube.com/embed/_YORKMfBxzE"],
    Zafina: ["https://www.youtube.com/embed/h-TcuAWV8ik"],
  },
  King: {
    Alisa: ["https://www.youtube.com/embed/e92Q_O0l7tk"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/pByVkb_h6xw"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/9vfwyqxI5Cc"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/eLNt9G7pqNQ"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/UO6NJdMvXeE"],
    Claudio: ["https://www.youtube.com/embed/cZFYOJn24CI"],
    Clive: ["https://www.youtube.com/embed/0fDg5e3biu4"],
    Devil: ["https://www.youtube.com/embed/2DiqKplwtjI"],
    Dragunov: ["https://www.youtube.com/embed/4yKorDwA3b8"],
    Eddy: ["https://www.youtube.com/embed/3e2wJLQkxMw"],
    Fahkumram:["https://www.youtube.com/embed/ADfLMVed83o"],
    Feng: ["https://www.youtube.com/embed/QSg-4Q0mebA"],
    Heihachi: ["https://www.youtube.com/embed/FFF75G1lt-Y"],
    Hwoarang: ["https://www.youtube.com/embed/LU98uuBtYX0"],
    Jack: ["https://www.youtube.com/embed/TE-je2OzE5s"],
    Jin: ["https://www.youtube.com/embed/Cvwhk7o-jUU"],
    Jun: ["https://www.youtube.com/embed/efQBgfmEDv0"],
    Kazuya: ["https://www.youtube.com/embed/2EuTfGzQzQQ"],
    King: ["https://www.youtube.com/embed/-0p4awN4k4c"],
    Kuma: ["https://www.youtube.com/embed/IwteZAev1eU"],
    Lars: ["https://www.youtube.com/embed/hfMiFe_nzgM"],
    Law: ["https://www.youtube.com/embed/TqPvO_zihGg"],
    Lee: ["https://www.youtube.com/embed/MzO-NA06Ggw"],
    Leo: ["https://www.youtube.com/embed/sB93MuYS778"],
    Leroy: ["https://www.youtube.com/embed/IYWFCPN1dhI"],
    Lidia: ["https://www.youtube.com/embed/AQw_Y4hlK68"],
    Lili: ["https://www.youtube.com/embed/yHYpQZAWDkg"],
    Nina: ["https://www.youtube.com/embed/2qUWfSO3oWk"],
    Panda: ["https://www.youtube.com/embed/KxqxbwtKHUQ"],
    Paul: ["https://www.youtube.com/embed/juAbVLA78jo"],
    Raven: ["https://www.youtube.com/embed/xCSv41M1yLQ"],
    Reina: ["https://www.youtube.com/embed/x4xciDJlu9g"],
    Shaheen: ["https://www.youtube.com/embed/huIHYZIVG80"],
    Steve: ["https://www.youtube.com/embed/QpfKNYu-JUc"],
    Victor: ["https://www.youtube.com/embed/rHUbyoDvKwk"],
    Xiaoyu: ["https://www.youtube.com/embed/eNif-xgNz2c"],
    Yoshimitsu: ["https://www.youtube.com/embed/up8iv6Se_VQ"],
    Zafina: ["https://www.youtube.com/embed/lwNDRCJCIwA"],
  },
  Kuma: {
    Alisa: ["https://www.youtube.com/embed/DoVMfRbarZE"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/hQFXaFo5SLQ"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/NEt-MR0nuKw"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/SalYmTWefxs"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/IXfl2Gx5k_4"],
    Claudio: ["https://www.youtube.com/embed/VibWC9afReA"],
    Clive: ["https://www.youtube.com/embed/D-uKbELuJHQ"],
    Devil: ["https://www.youtube.com/embed/wuoxjQFgqXk"],
    Dragunov: ["https://www.youtube.com/embed/T4TegaoNKd8"],
    Eddy: ["https://www.youtube.com/embed/XyAGC6A4jRo"],
    Fahkumram:[],
    Feng: ["https://www.youtube.com/embed/SbQv0ke6FMg"],
    Heihachi: ["https://www.youtube.com/embed/NSMi2NcjgQQ"],
    Hwoarang: ["https://www.youtube.com/embed/pzXw9V_34j8"],
    Jack: ["https://www.youtube.com/embed/BkJNXGMNuFQ"],
    Jin: ["https://www.youtube.com/embed/o7uQ27-FCks"],
    Jun: ["https://www.youtube.com/embed/_cWPxsT1SFw"],
    Kazuya: ["https://www.youtube.com/embed/2EuTfGzQzQQ"],
    King: ["https://www.youtube.com/embed/IwteZAev1eU"],
    Kuma: ["https://www.youtube.com/embed/u5q5zDkTR64"],
    Lars: ["https://www.youtube.com/embed/xmLJbiGwJCU"],
    Law: ["https://www.youtube.com/embed/iPvjkF-qjeY"],
    Lee: ["https://www.youtube.com/embed/2tvlz3VMoMw"],
    Leo: ["https://www.youtube.com/embed/tlo3kWwXYJk"],
    Leroy: ["https://www.youtube.com/embed/NW6TQuYPeyI"],
    Lidia: ["https://www.youtube.com/embed/6CX9Bk3rMcc"],
    Lili: ["https://www.youtube.com/embed/PIM173NfY24"],
    Nina: ["https://www.youtube.com/embed/26w8zdbgP2c"],
    Panda: ["https://www.youtube.com/embed/W77uYEeIfMM"],
    Paul: ["https://www.youtube.com/embed/hsUra1lfSG0"],
    Raven: ["https://www.youtube.com/embed/cG4mOrK8aN0"],
    Reina: ["https://www.youtube.com/embed/srwjQYmnPW4"],
    Shaheen: ["https://www.youtube.com/embed/QacppaF1L_g"],
    Steve: ["https://www.youtube.com/embed/qMO_S7CFb1o"],
    Victor: ["https://www.youtube.com/embed/AHauCZGrFuE"],
    Xiaoyu: ["https://www.youtube.com/embed/Qg-BN9SfWHs"],
    Yoshimitsu: ["https://www.youtube.com/embed/YqGX6CYCvpg"],
    Zafina: ["https://www.youtube.com/embed/7DlaStMeIBM"],
  },
  Lars: {
    Alisa: ["https://www.youtube.com/embed/sP20NMwxD9Q"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/x4EnUZvq6dM"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/jzX2kTZnHGE"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/-Ys04NLqHwc"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/NIWRMvdp6-4"],
    Claudio: ["https://www.youtube.com/embed/6eiNb8Ou_h4"],
    Clive: ["https://www.youtube.com/embed/uDntqPD1UWA"],
    Devil: ["https://www.youtube.com/embed/UBFShZSXrg0"],
    Dragunov: ["https://www.youtube.com/embed/B38yY_CN2gc"],
    Eddy: ["https://www.youtube.com/embed/vM2tJ80slNU"],
    Fahkumram:["https://www.youtube.com/embed/B_lN9-oyrM4"],
    Feng: ["https://www.youtube.com/embed/G8N1ZmFW4vo"],
    Heihachi: ["https://www.youtube.com/embed/fbvinXHTrpc"],
    Hwoarang: ["https://www.youtube.com/embed/ElkPLEK-MuI"],
    Jack: ["https://www.youtube.com/embed/MmAvuQFLDOc"],
    Jin: ["https://www.youtube.com/embed/0HdVE6HtAm0"],
    Jun: ["https://www.youtube.com/embed/fa85CXYSE30"],
    Kazuya: ["https://www.youtube.com/embed/rZfnao93o_w"],
    King: ["https://www.youtube.com/embed/hfMiFe_nzgM"],
    Kuma: ["https://www.youtube.com/embed/xmLJbiGwJCU"],
    Lars: ["https://www.youtube.com/embed/TEA80Y-dQVA"],
    Law: ["https://www.youtube.com/embed/dQ7agXaegsQ"],
    Lee: ["https://www.youtube.com/embed/Z98i5cQYpNY"],
    Leo: ["https://www.youtube.com/embed/FgHYg-BX8e4"],
    Leroy: ["https://www.youtube.com/embed/WJkfy_xsWV0"],
    Lidia: ["https://www.youtube.com/embed/Nn3M3eC0aUM"],
    Lili: ["https://www.youtube.com/embed/eQ22MeUbzis"],
    Nina: ["https://www.youtube.com/embed/ko14INSYWQo"],
    Panda: ["https://www.youtube.com/embed/fVhmOYHek6g"],
    Paul: ["https://www.youtube.com/embed/-sGGxZ8KSag"],
    Raven: ["https://www.youtube.com/embed/OoZzLLRKXaE"],
    Reina: ["https://www.youtube.com/embed/bKgc1faxer0"],
    Shaheen: ["https://www.youtube.com/embed/i27J0ezT1XQ"],
    Steve: ["https://www.youtube.com/embed/K52CnPap1zg"],
    Victor: ["https://www.youtube.com/embed/95Du9yRWMMQ"],
    Xiaoyu: ["https://www.youtube.com/embed/5rT-R6Lst2M"],
    Yoshimitsu: ["https://www.youtube.com/embed/2fMZWkztGcs"],
    Zafina: ["https://www.youtube.com/embed/6f7bf5QGgEA"],
  },
  Law: {
    Alisa: ["https://www.youtube.com/embed/UcAEEJ-trKg"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/UP96gKHUUpg"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/eUgB0fiCnbw"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/4duUAnejKKI"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/dMKPWlSxoh8"],
    Claudio: ["https://www.youtube.com/embed/auVwyNOdyXc"],
    Clive: ["https://www.youtube.com/embed/P2682s36NVc"],
    Devil: ["https://www.youtube.com/embed/cHywJu9eKfo"],
    Dragunov: ["https://www.youtube.com/embed/_CWzUMLFkAc"],
    Eddy: ["https://www.youtube.com/embed/ZbI4W_VaQ2Y"],
    Fahkumram:["https://www.youtube.com/embed/W2eA6mArlaM"],
    Feng: ["https://www.youtube.com/embed/SbPtJGZD3Ns"],
    Heihachi: ["https://www.youtube.com/embed/1-XWqoJdXqY"],
    Hwoarang: ["https://www.youtube.com/embed/V697wVUr9CI"],
    Jack: ["https://www.youtube.com/embed/736FTLmoPqo"],
    Jin: ["https://www.youtube.com/embed/4Av2dIAI_Ac"],
    Jun: ["https://www.youtube.com/embed/KwyzAK08_xY"],
    Kazuya: ["https://www.youtube.com/embed/ebH1WOlX3mQ"],
    King: ["https://www.youtube.com/embed/TqPvO_zihGg"],
    Kuma: ["https://www.youtube.com/embed/iPvjkF-qjeY"],
    Lars: ["https://www.youtube.com/embed/dQ7agXaegsQ"],
    Law: ["https://www.youtube.com/embed/rVsgR9Caov0"],
    Lee: ["https://www.youtube.com/embed/tGo7nMxG6bI"],
    Leo: ["https://www.youtube.com/embed/hjJoyrj7yrI"],
    Leroy: ["https://www.youtube.com/embed/6675HE4DnUs"],
    Lidia: ["https://www.youtube.com/embed/EjBnWUXWTp8"],
    Lili: ["https://www.youtube.com/embed/4l8UgzCIbwY"],
    Nina: ["https://www.youtube.com/embed/_ayoGO1mOXs"],
    Panda: ["https://www.youtube.com/embed/CXJuaUqb4Nc"],
    Paul: ["https://www.youtube.com/embed/xu_ibq3Pmek"],
    Raven: ["https://www.youtube.com/embed/UIBnrZuvUZ0"],
    Reina: ["https://www.youtube.com/embed/uI1Sm1LZHL4"],
    Shaheen: ["https://www.youtube.com/embed/voKUjaB2nDA"],
    Steve: ["https://www.youtube.com/embed/YYLVlxkk430"],
    Victor: ["https://www.youtube.com/embed/uu6kNVgwuiQ"],
    Xiaoyu: ["https://www.youtube.com/embed/pFhsdJQAUaA"],
    Yoshimitsu: ["https://www.youtube.com/embed/bSR5Kr5e08c"],
    Zafina: ["https://www.youtube.com/embed/aM9ZkijYSzM"],
  },
  Lee: {
    Alisa: ["https://www.youtube.com/embed/ISpLais1f28"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/DbbLFTxF--8"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/KkB7IwtAmqY"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/taxA0F0X8Lc"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/yXIHycRrqmQ"],
    Claudio: ["https://www.youtube.com/embed/BGWgsH0_ucA"],
    Clive: ["https://www.youtube.com/embed/iZQotPvEcN4"],
    Devil: ["https://www.youtube.com/embed/SeGqSsyFd1k"],
    Dragunov: ["https://www.youtube.com/embed/NnaVfl5kTZw"],
    Eddy: ["https://www.youtube.com/embed/IigpfkgLXF8"],
    Fahkumram:["https://www.youtube.com/embed/4Y768Fx8juw"],
    Feng: ["https://www.youtube.com/embed/E0bNLZvtkwU"],
    Heihachi: ["https://www.youtube.com/embed/8vIm-To8wEM"],
    Hwoarang: ["https://www.youtube.com/embed/SCwtNWr7BZY"],
    Jack: ["https://www.youtube.com/embed/X-Q5iVvuCW0"],
    Jin: ["https://www.youtube.com/embed/Ntk-rzJWxFs"],
    Jun: ["https://www.youtube.com/embed/MjXx1NXsJ3A"],
    Kazuya: ["https://www.youtube.com/embed/plVGmLVsS-I"],
    King: ["https://www.youtube.com/embed/MzO-NA06Ggw"],
    Kuma: ["https://www.youtube.com/embed/2tvlz3VMoMw"],
    Lars: ["https://www.youtube.com/embed/Z98i5cQYpNY"],
    Law: ["https://www.youtube.com/embed/tGo7nMxG6bI"],
    Lee: ["https://www.youtube.com/embed/cXAqsimWhZU"],
    Leo: ["https://www.youtube.com/embed/aobdLzBtlFw"],
    Leroy: ["https://www.youtube.com/embed/Or1FMbFdcR4"],
    Lidia: ["https://www.youtube.com/embed/KHA0wITo_8U"],
    Lili: ["https://www.youtube.com/embed/cx3DEIVllR4"],
    Nina: ["https://www.youtube.com/embed/rNF3oXBaTrs"],
    Panda: ["https://www.youtube.com/embed/yRh_njrmCj8"],
    Paul: ["https://www.youtube.com/embed/rvxYNqr-oOM"],
    Raven: ["https://www.youtube.com/embed/0YgkS9PYqh8"],
    Reina: ["https://www.youtube.com/embed/iPUeczOg9BU"],
    Shaheen: ["https://www.youtube.com/embed/HzwcP8LHN2E"],
    Steve: ["https://www.youtube.com/embed/2hF7wVatUkM"],
    Victor: ["https://www.youtube.com/embed/olazRnfpmks"],
    Xiaoyu: ["https://www.youtube.com/embed/0rc6o3jk1JM"],
    Yoshimitsu: ["https://www.youtube.com/embed/DQwtSWqt1wc"],
    Zafina: ["https://www.youtube.com/embed/Bj3OeCooaSw"],
  },
  Leo: {
    Alisa: ["https://www.youtube.com/embed/Ljmx5JpSPe0"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/ByCgQFFYUVo"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/1NBQX-cbe6I"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/JW1sGp38dzc"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/KfRKtn8QRAo"],
    Claudio: ["https://www.youtube.com/embed/Eoj2Nn2JkgA"],
    Clive: ["https://www.youtube.com/embed/UOtRbsF5tsk"],
    Devil: ["https://www.youtube.com/embed/kSfdAAm5O2A"],
    Dragunov: ["https://www.youtube.com/embed/ZRnuQGaInGM"],
    Eddy: ["https://www.youtube.com/embed/wH4sPAtS0KY"],
    Fahkumram:["https://www.youtube.com/embed/z4MPNUTTxEs"],
    Feng: ["https://www.youtube.com/embed/PL2_7R_RFW8"],
    Heihachi: ["https://www.youtube.com/embed/Bum_r8G9yjQ"],
    Hwoarang: ["https://www.youtube.com/embed/G_lx1th04T8"],
    Jack: ["https://www.youtube.com/embed/ei1GQjj_x8g"],
    Jin: ["https://www.youtube.com/embed/nVxqHK7RnG4"],
    Jun: ["https://www.youtube.com/embed/GLDJ14vGpjA"],
    Kazuya: ["https://www.youtube.com/embed/Ng5h9vvif0A"],
    King: ["https://www.youtube.com/embed/sB93MuYS778"],
    Kuma: ["https://www.youtube.com/embed/tlo3kWwXYJk"],
    Lars: ["https://www.youtube.com/embed/FgHYg-BX8e4"],
    Law: ["https://www.youtube.com/embed/hjJoyrj7yrI"],
    Lee: ["https://www.youtube.com/embed/aobdLzBtlFw"],
    Leo: ["https://www.youtube.com/embed/jO2xxCdaZ08"],
    Leroy: ["https://www.youtube.com/embed/McEsE0WC_R0"],
    Lidia: ["https://www.youtube.com/embed/lJeo0h9EOyc"],
    Lili: ["https://www.youtube.com/embed/7nWKwWi6guE"],
    Nina: ["https://www.youtube.com/embed/Yij_-FXSBsQ"],
    Panda: ["https://www.youtube.com/embed/0BKKt26wRfA"],
    Paul: ["https://www.youtube.com/embed/_vnoPbmS4J8"],
    Raven: ["https://www.youtube.com/embed/bZuSCgEIpuo"],
    Reina: ["https://www.youtube.com/embed/HSpL06ik2j0"],
    Shaheen: ["https://www.youtube.com/embed/XgeOTLcHoiQ"],
    Steve: ["https://www.youtube.com/embed/HNDkfNyQnys"],
    Victor: ["https://www.youtube.com/embed/OmgZ9pYo9qM"],
    Xiaoyu: ["https://www.youtube.com/embed/U637FKS9c-c"],
    Yoshimitsu: ["https://www.youtube.com/embed/fTzzGV7nsiQ"],
    Zafina: ["https://www.youtube.com/embed/z3p9ch0dxFU"],
  },
  Leroy: {
    Alisa: ["https://www.youtube.com/embed/UhR41T94vp0"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/FuDQ5OaHAVA"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/TM5d6n6V4bs"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/yb9VtUO2Gvw"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/43qrOAtx2u4"],
    Claudio: ["https://www.youtube.com/embed/hCelXuKJFi0"],
    Clive: ["https://www.youtube.com/embed/ulA-e4XEr_s"],
    Devil: ["https://www.youtube.com/embed/8fawaWcyVoM"],
    Dragunov: ["https://www.youtube.com/embed/3T3BfAq0DpU"],
    Eddy: ["https://www.youtube.com/embed/3adYTII2i7M"],
    Fahkumram:["https://www.youtube.com/embed/6hmQl5W29i8"],
    Feng: ["https://www.youtube.com/embed/vn7NjzRMZo4"],
    Heihachi: ["https://www.youtube.com/embed/g-0iCwzkKbM"],
    Hwoarang: ["https://www.youtube.com/embed/S93G04KUiy4"],
    Jack: ["https://www.youtube.com/embed/4yHOQyRBYiQ"],
    Jin: ["https://www.youtube.com/embed/zVkNldSvPlk"],
    Jun: ["https://www.youtube.com/embed/LaSl2lqKgHs"],
    Kazuya: ["https://www.youtube.com/embed/HKPeQuFKoGI"],
    King: ["https://www.youtube.com/embed/IYWFCPN1dhI"],
    Kuma: ["https://www.youtube.com/embed/NW6TQuYPeyI"],
    Lars: ["https://www.youtube.com/embed/WJkfy_xsWV0"],
    Law: ["https://www.youtube.com/embed/6675HE4DnUs"],
    Lee: ["https://www.youtube.com/embed/Or1FMbFdcR4"],
    Leo: ["https://www.youtube.com/embed/McEsE0WC_R0"],
    Leroy: ["https://www.youtube.com/embed/o82rR4hTe4c"],
    Lidia: ["https://www.youtube.com/embed/5SfJ1m7zueU"],
    Lili: ["https://www.youtube.com/embed/eTiqz1ilDbc"],
    Nina: ["https://www.youtube.com/embed/95IIllnNr2A"],
    Panda: ["https://www.youtube.com/embed/4kQ7cp5_QDk"],
    Paul: ["https://www.youtube.com/embed/CXZqW2kc5sk"],
    Raven: ["https://www.youtube.com/embed/A8yAzgbbsvg"],
    Reina: ["https://www.youtube.com/embed/B0B8Nezm0JI"],
    Shaheen: ["https://www.youtube.com/embed/GBKMqrgQH78"],
    Steve: ["https://www.youtube.com/embed/akIhEdVok1U"],
    Victor: ["https://www.youtube.com/embed/lqTrEGrSL_8"],
    Xiaoyu: ["https://www.youtube.com/embed/UEdq_LqW5i0"],
    Yoshimitsu: ["https://www.youtube.com/embed/W7TJ7TgiCFo"],
    Zafina: ["https://www.youtube.com/embed/TahtBop1mdI"],
  },
  Lidia: {
    Alisa: ["https://www.youtube.com/embed/BFraTYqzSFg"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/DXJ1C-jY_LU"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/0gEGFv1Dkn8"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/d7hm0q_cn2A"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/GFI35uHOsww"],
    Claudio: ["https://www.youtube.com/embed/aUF6UKZ-y80"],
    Clive: ["https://www.youtube.com/embed/N0PUTsPHK7o"],
    Devil: ["https://www.youtube.com/embed/SUjfXyUp3uI"],
    Dragunov: ["https://www.youtube.com/embed/YMkzGgYRyYE"],
    Eddy: ["https://www.youtube.com/embed/gs0mYxJkKa8"],
    Fahkumram:["https://www.youtube.com/embed/cDptee2kMBE"],
    Feng: ["https://www.youtube.com/embed/o5lnns2v9XM"],
    Heihachi: ["https://www.youtube.com/embed/m_KDVgt3Ulc"],
    Hwoarang: ["https://www.youtube.com/embed/jAAGKivN-BA"],
    Jack: ["https://www.youtube.com/embed/1VbHaFANxgQ"],
    Jin: ["https://www.youtube.com/embed/QTAJ1AfA6RE"],
    Jun: ["https://www.youtube.com/embed/NG5nepgT6uI"],
    Kazuya: ["https://www.youtube.com/embed/sCioC-gqG3A"],
    King: ["https://www.youtube.com/embed/AQw_Y4hlK68"],
    Kuma: ["https://www.youtube.com/embed/6CX9Bk3rMcc"],
    Lars: ["https://www.youtube.com/embed/Nn3M3eC0aUM"],
    Law: ["https://www.youtube.com/embed/EjBnWUXWTp8"],
    Lee: ["https://www.youtube.com/embed/KHA0wITo_8U"],
    Leo: ["https://www.youtube.com/embed/lJeo0h9EOyc"],
    Leroy: ["https://www.youtube.com/embed/5SfJ1m7zueU"],
    Lidia: ["https://www.youtube.com/embed/qS5NQIH51As"],
    Lili: ["https://www.youtube.com/embed/FJ8LtzflKsg"],
    Nina: ["https://www.youtube.com/embed/OuLiLGDiEQQ"],
    Panda: ["https://www.youtube.com/embed/3UIlty_uG80"],
    Paul: ["https://www.youtube.com/embed/CIklPD5JHzc"],
    Raven: ["https://www.youtube.com/embed/5ELQXCSi2Xo"],
    Reina: ["https://www.youtube.com/embed/Zl2wxFGODcs"],
    Shaheen: ["https://www.youtube.com/embed/ODItxfszB78"],
    Steve: ["https://www.youtube.com/embed/iG2i8vCpv2M"],
    Victor: ["https://www.youtube.com/embed/5pwmTsmFXIU"],
    Xiaoyu: ["https://www.youtube.com/embed/O3WCk5zGs_I"],
    Yoshimitsu: ["https://www.youtube.com/embed/iRRtajwiPzY"],
    Zafina: ["https://www.youtube.com/embed/Pam_zy3TnXg"],
  },
  Lili: {
    Alisa: ["https://www.youtube.com/embed/K5Ikg9zdbKM"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/3VZXB0VTSmA"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/TsBw5igzSHE"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/5_1ZB8xtWYM"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/LoFlPI78Lrg"],
    Claudio: ["https://www.youtube.com/embed/KMKSIxrzRzE"],
    Clive: ["https://www.youtube.com/embed/iFngzx3RiGY"],
    Devil: ["https://www.youtube.com/embed/cVsW7aLjRHQ"],
    Dragunov: ["https://www.youtube.com/embed/roajOB02Wvk"],
    Eddy: ["https://www.youtube.com/embed/X68ofpABqJE"],
    Fahkumram:["https://www.youtube.com/embed/5qUtDa5xbfc"],
    Feng: ["https://www.youtube.com/embed/XkS4qPZumpc"],
    Heihachi: ["https://www.youtube.com/embed/yoT5nXGH08M"],
    Hwoarang: ["https://www.youtube.com/embed/MEIIkcNvTHM"],
    Jack: ["https://www.youtube.com/embed/lQQ96NZF0IM"],
    Jin: ["https://www.youtube.com/embed/F06Q9sobIK4"],
    Jun: ["https://www.youtube.com/embed/eFLk2ydSaS0"],
    Kazuya: ["https://www.youtube.com/embed/9gJzSAvJ__E"],
    King: ["https://www.youtube.com/embed/yHYpQZAWDkg"],
    Kuma: ["https://www.youtube.com/embed/PIM173NfY24"],
    Lars: ["https://www.youtube.com/embed/eQ22MeUbzis"],
    Law: ["https://www.youtube.com/embed/4l8UgzCIbwY"],
    Lee: ["https://www.youtube.com/embed/cx3DEIVllR4"],
    Leo: ["https://www.youtube.com/embed/7nWKwWi6guE"],
    Leroy: ["https://www.youtube.com/embed/eTiqz1ilDbc"],
    Lidia: ["https://www.youtube.com/embed/FJ8LtzflKsg"],
    Lili: ["https://www.youtube.com/embed/AbDG6_EXFbQ"],
    Nina: ["https://www.youtube.com/embed/15qqk5gd5ig"],
    Panda: ["https://www.youtube.com/embed/FN2WVPs0078"],
    Paul: ["https://www.youtube.com/embed/JtWFMRZmOjE"],
    Raven: ["https://www.youtube.com/embed/af-PNSKkt6s"],
    Reina: ["https://www.youtube.com/embed/ApvO5hASwcs"],
    Shaheen: ["https://www.youtube.com/embed/5FuCtwaSpAE"],
    Steve: ["https://www.youtube.com/embed/rlez6al2tac"],
    Victor: ["https://www.youtube.com/embed/qzudEIV3U18"],
    Xiaoyu: ["https://www.youtube.com/embed/XE_G1-Vdwf4"],
    Yoshimitsu: ["https://www.youtube.com/embed/9wSHDi4xVJs"],
    Zafina: ["https://www.youtube.com/embed/UBV4qrgTsOo"],
  },
  Nina: {
    Alisa: ["https://www.youtube.com/embed/eo8hn-C5oGk"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/nMhMnlriha0"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/tiXakl6znzI"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/yF-sNnGG6i4"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/26P3_zi3uIU"],
    Claudio: ["https://www.youtube.com/embed/FOS3_qTRMfA"],
    Clive: ["https://www.youtube.com/embed/D2VS1kTotS0"],
    Devil: ["https://www.youtube.com/embed/5ssyDi1AKAI"],
    Dragunov: ["https://www.youtube.com/embed/BvHtH7GKPhQ"],
    Eddy: ["https://www.youtube.com/embed/CHRtZ3IOkT0"],
    Fahkumram:["https://www.youtube.com/embed/roPbKSU9K80"],
    Feng: ["https://www.youtube.com/embed/0oVckKCkZFE"],
    Heihachi: ["https://www.youtube.com/embed/EGC2ZjjbZ30"],
    Hwoarang: ["https://www.youtube.com/embed/fxiMTNmHXZE"],
    Jack: ["https://www.youtube.com/embed/aQWX2pa8qZY"],
    Jin: ["https://www.youtube.com/embed/ZqI5UOelaVw"],
    Jun: ["https://www.youtube.com/embed/hGQ-0SQDlh0"],
    Kazuya: ["https://www.youtube.com/embed/CIT30BaKajw"],
    King: ["https://www.youtube.com/embed/2qUWfSO3oWk"],
    Kuma: ["https://www.youtube.com/embed/26w8zdbgP2c"],
    Lars: ["https://www.youtube.com/embed/ko14INSYWQo"],
    Law: ["https://www.youtube.com/embed/_ayoGO1mOXs"],
    Lee: ["https://www.youtube.com/embed/rNF3oXBaTrs"],
    Leo: ["https://www.youtube.com/embed/Yij_-FXSBsQ"],
    Leroy: ["https://www.youtube.com/embed/95IIllnNr2A"],
    Lidia: ["https://www.youtube.com/embed/OuLiLGDiEQQ"],
    Lili: ["https://www.youtube.com/embed/15qqk5gd5ig"],
    Nina: ["https://www.youtube.com/embed/eHgcUxtw-3U"],
    Panda: ["https://www.youtube.com/embed/4gQerL94Jq8"],
    Paul: ["https://www.youtube.com/embed/TEJoCAqycVI"],
    Raven: ["https://www.youtube.com/embed/spkJalxkNDg"],
    Reina: ["https://www.youtube.com/embed/YEkztpztsU4"],
    Shaheen: ["https://www.youtube.com/embed/jmKSMNArC44"],
    Steve: ["https://www.youtube.com/embed/5N7ejPlvAA0"],
    Victor: ["https://www.youtube.com/embed/pg9pIgJjzDM"],
    Xiaoyu: ["https://www.youtube.com/embed/r_U3deGuFYw"],
    Yoshimitsu: ["https://www.youtube.com/embed/MwO2s1F31Mg"],
    Zafina: ["https://www.youtube.com/embed/ryEYjjruouY"],
  },
  Panda: {
    Alisa: ["https://www.youtube.com/embed/xptlM3wNtgA"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/NDke4TqiUEA"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/WNGO9b32Xc4"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/dxScAYrRQ5k"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/9S_HgpEHwCM"],
    Claudio: ["https://www.youtube.com/embed/vhKySRczay0"],
    Clive: ["https://www.youtube.com/embed/IjqzYHUFXFc"],
    Devil: ["https://www.youtube.com/embed/gyAAKCOyrm8"],
    Dragunov: ["https://www.youtube.com/embed/9R1TUAXROEo"],
    Eddy: ["https://www.youtube.com/embed/-Go6KkzshPI"],
    Fahkumram:["https://www.youtube.com/embed/hhx_IMA3Owg"],
    Feng: ["https://www.youtube.com/embed/LcIEpWTU76c"],
    Heihachi: ["https://www.youtube.com/embed/93hq0YU3Gqk"],
    Hwoarang: ["https://www.youtube.com/embed/YdqST5-1HQ0"],
    Jack: ["https://www.youtube.com/embed/Nf7vfOoZOic"],
    Jin: ["https://www.youtube.com/embed/CnodrWllzO0"],
    Jun: ["https://www.youtube.com/embed/EFwePQnvRoM"],
    Kazuya: ["https://www.youtube.com/embed/iqlVhvGK0iE"],
    King: ["https://www.youtube.com/embed/KxqxbwtKHUQ"],
    Kuma: ["https://www.youtube.com/embed/W77uYEeIfMM"],
    Lars: ["https://www.youtube.com/embed/fVhmOYHek6g"],
    Law: ["https://www.youtube.com/embed/CXJuaUqb4Nc"],
    Lee: ["https://www.youtube.com/embed/yRh_njrmCj8"],
    Leo: ["https://www.youtube.com/embed/0BKKt26wRfA"],
    Leroy: ["https://www.youtube.com/embed/4kQ7cp5_QDk"],
    Lidia: ["https://www.youtube.com/embed/3UIlty_uG80"],
    Lili: ["https://www.youtube.com/embed/FN2WVPs0078"],
    Nina: ["https://www.youtube.com/embed/4gQerL94Jq8"],
    Panda: ["https://www.youtube.com/embed/o_ltFzhw7pg"],
    Paul: ["https://www.youtube.com/embed/LaOOj7jyHrY"],
    Raven: ["https://www.youtube.com/embed/79vHiFjXNOc"],
    Reina: ["https://www.youtube.com/embed/xFSOtUTLEZU"],
    Shaheen: ["https://www.youtube.com/embed/LOLXAA-eyTI"],
    Steve: ["https://www.youtube.com/embed/aOlj-6u67Fc"],
    Victor: ["https://www.youtube.com/embed/tlQ6Qa9g7gM"],
    Xiaoyu: ["https://www.youtube.com/embed/8p9bv0OpF1Q"],
    Yoshimitsu: ["https://www.youtube.com/embed/YZYRsp3xcAE"],
    Zafina: ["https://www.youtube.com/embed/ERy-51rjpMw"],
  },
  Paul: {
    Alisa: ["https://www.youtube.com/embed/ujtdTwR6Axo"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/SIGh-AO10sY"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/SAUD4pwUahA"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/U1ERpZrb6BQ"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/v8wSSJ_iQmU"],
    Claudio: ["https://www.youtube.com/embed/Q1MHIsGOhGM"],
    Clive: ["https://www.youtube.com/embed/WCK8SA5zh30"],
    Devil: ["https://www.youtube.com/embed/He8n1tOqIEU"],
    Dragunov: ["https://www.youtube.com/embed/AFV_YwLOzJ0"],
    Eddy: ["https://www.youtube.com/embed/9uYESKCFKtQ"],
    Fahkumram:["https://www.youtube.com/embed/akX69ULr60w"],
    Feng: ["https://www.youtube.com/embed/C-9SseDU3tU"],
    Heihachi: ["https://www.youtube.com/embed/B0Xat6dF-QM"],
    Hwoarang: ["https://www.youtube.com/embed/nXb2rEwXz6c"],
    Jack: ["https://www.youtube.com/embed/OfQwomhE95E"],
    Jin: ["https://www.youtube.com/embed/zoPjtmlQjQQ"],
    Jun: ["https://www.youtube.com/embed/ey0iooo5rxk"],
    Kazuya: ["https://www.youtube.com/embed/gOo77gBorGE"],
    King: ["https://www.youtube.com/embed/juAbVLA78jo"],
    Kuma: ["https://www.youtube.com/embed/hsUra1lfSG0"],
    Lars: ["https://www.youtube.com/embed/-sGGxZ8KSag"],
    Law: ["https://www.youtube.com/embed/xu_ibq3Pmek"],
    Lee: ["https://www.youtube.com/embed/rvxYNqr-oOM"],
    Leo: ["https://www.youtube.com/embed/_vnoPbmS4J8"],
    Leroy: ["https://www.youtube.com/embed/CXZqW2kc5sk"],
    Lidia: ["https://www.youtube.com/embed/CIklPD5JHzc"],
    Lili: ["https://www.youtube.com/embed/JtWFMRZmOjE"],
    Nina: ["https://www.youtube.com/embed/TEJoCAqycVI"],
    Panda: ["https://www.youtube.com/embed/LaOOj7jyHrY"],
    Paul: ["https://www.youtube.com/embed/RqgpbbR8ZT0"],
    Raven: ["https://www.youtube.com/embed/UdFkTDmcPVI"],
    Reina: ["https://www.youtube.com/embed/PTt3Emyte40"],
    Shaheen: ["https://www.youtube.com/embed/_ffNYhbtvPM"],
    Steve: ["https://www.youtube.com/embed/0vR8VqwXIpU"],
    Victor: ["https://www.youtube.com/embed/zm8C1Rk5xlc"],
    Xiaoyu: ["https://www.youtube.com/embed/hLTYsC_k9Rs"],
    Yoshimitsu: ["https://www.youtube.com/embed/ah6N0wkNE3M"],
    Zafina: ["https://www.youtube.com/embed/sE6sGW4gV-U"],
  },
  Raven: {
    Alisa: ["https://www.youtube.com/embed/OXHcCcgqmro"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/89nrEsGZ_HA"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/LtOFS194zNo"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/9DMhy0rkrcs"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/vHbKq_xkuVM"],
    Claudio: ["https://www.youtube.com/embed/XW4H0JGLevY"],
    Clive: ["https://www.youtube.com/embed/AX_Ie7PKrYk"],
    Devil: ["https://www.youtube.com/embed/KW6ecZx_qDU"],
    Dragunov: ["https://www.youtube.com/embed/7CHxzcQaebI"],
    Eddy: ["https://www.youtube.com/embed/LFgJaCSlNTs"],
    Fahkumram:["https://www.youtube.com/embed/ym_LngGoYzw"],
    Feng: ["https://www.youtube.com/embed/vvBRz4nrEbk"],
    Heihachi: ["https://www.youtube.com/embed/TNg1J7okZgM"],
    Hwoarang: ["https://www.youtube.com/embed/2Dgecb_Wfjo"],
    Jack: ["https://www.youtube.com/embed/y3GWHpbfXfE"],
    Jin: ["https://www.youtube.com/embed/lpsiKNbR72U"],
    Jun: ["https://www.youtube.com/embed/onbMCTQFSu8"],
    Kazuya: ["https://www.youtube.com/embed/gZv9HDIF8Sc"],
    King: ["https://www.youtube.com/embed/xCSv41M1yLQ"],
    Kuma: ["https://www.youtube.com/embed/cG4mOrK8aN0"],
    Lars: ["https://www.youtube.com/embed/OoZzLLRKXaE"],
    Law: ["https://www.youtube.com/embed/UIBnrZuvUZ0"],
    Lee: ["https://www.youtube.com/embed/0YgkS9PYqh8"],
    Leo: ["https://www.youtube.com/embed/bZuSCgEIpuo"],
    Leroy: ["https://www.youtube.com/embed/A8yAzgbbsvg"],
    Lidia: ["https://www.youtube.com/embed/5ELQXCSi2Xo"],
    Lili: ["https://www.youtube.com/embed/af-PNSKkt6s"],
    Nina: ["https://www.youtube.com/embed/spkJalxkNDg"],
    Panda: ["https://www.youtube.com/embed/79vHiFjXNOc"],
    Paul: ["https://www.youtube.com/embed/UdFkTDmcPVI"],
    Raven: ["https://www.youtube.com/embed/bgJj1xe222c"],
    Reina: ["https://www.youtube.com/embed/yrmCJ66VQbc"],
    Shaheen: ["https://www.youtube.com/embed/pCvnhfJ4Y4M"],
    Steve: ["https://www.youtube.com/embed/ypC3I50LK0c"],
    Victor: ["https://www.youtube.com/embed/4ZhRrW-cFhU"],
    Xiaoyu: ["https://www.youtube.com/embed/cOhbc8PcRhs"],
    Yoshimitsu: ["https://www.youtube.com/embed/R2kSBptlUQA"],
    Zafina: ["https://www.youtube.com/embed/aWCTS1bNmHQ"],
  },
  Reina: {
    Alisa: ["https://www.youtube.com/embed/QQ9uEcazyQk"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/T__scyDvTrU"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/eYX7vd_7D2c"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/sOs-rLWl6r8"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/DtVUoO3kR5U"],
    Claudio: ["https://www.youtube.com/embed/jQ6ZtTx373A"],
    Clive: ["https://www.youtube.com/embed/aN2B0qBjvpI"],
    Devil: ["https://www.youtube.com/embed/K4xhIpUfsy8"],
    Dragunov: ["https://www.youtube.com/embed/c7eoMXwoehs"],
    Eddy: ["https://www.youtube.com/embed/mMvm-Efl9iw"],
    Fahkumram:["https://www.youtube.com/embed/y5yfw64ipUI"],
    Feng: ["https://www.youtube.com/embed/D1EqdfTRpZU"],
    Heihachi: ["https://www.youtube.com/embed/usLxVbzCYNo"],
    Hwoarang: ["https://www.youtube.com/embed/pjD8KJbxcKE"],
    Jack: ["https://www.youtube.com/embed/Hp50kY3ZXd0"],
    Jin: ["https://www.youtube.com/embed/SHZQ9wcStAc"],
    Jun: ["https://www.youtube.com/embed/lIDh9hkYgbw"],
    Kazuya: ["https://www.youtube.com/embed/VYGyeLBkYR8"],
    King: ["https://www.youtube.com/embed/x4xciDJlu9g"],
    Kuma: ["https://www.youtube.com/embed/srwjQYmnPW4"],
    Lars: ["https://www.youtube.com/embed/bKgc1faxer0"],
    Law: ["https://www.youtube.com/embed/uI1Sm1LZHL4"],
    Lee: ["https://www.youtube.com/embed/iPUeczOg9BU"],
    Leo: ["https://www.youtube.com/embed/HSpL06ik2j0"],
    Leroy: ["https://www.youtube.com/embed/B0B8Nezm0JI"],
    Lidia: ["https://www.youtube.com/embed/Zl2wxFGODcs"],
    Lili: ["https://www.youtube.com/embed/ApvO5hASwcs"],
    Nina: ["https://www.youtube.com/embed/YEkztpztsU4"],
    Panda: ["https://www.youtube.com/embed/xFSOtUTLEZU"],
    Paul: ["https://www.youtube.com/embed/PTt3Emyte40"],
    Raven: ["https://www.youtube.com/embed/yrmCJ66VQbc"],
    Reina: ["https://www.youtube.com/embed/51R8k1ujFkI"],
    Shaheen: ["https://www.youtube.com/embed/Cs7snBXr6bU"],
    Steve: ["https://www.youtube.com/embed/CquIwouiAOA"],
    Victor: ["https://www.youtube.com/embed/l3XcsTb0DvA"],
    Xiaoyu: ["https://www.youtube.com/embed/eK2eJgW6Jyw"],
    Yoshimitsu: ["https://www.youtube.com/embed/g-ht9nt3cQE"],
    Zafina: ["https://www.youtube.com/embed/1-AsiTCbq1w"],
  },
  Shaheen: {
    Alisa: ["https://www.youtube.com/embed/R7E6cY0Q4Lk"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/yFOCxnzpCMY"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/Xgm0XJau8ZU"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/nnLld581f04"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/3IxZdjDwoxQ"],
    Claudio: ["https://www.youtube.com/embed/W9d-Yoe_P-Q"],
    Clive: ["https://www.youtube.com/embed/Poy83jzMGZw"],
    Devil: ["https://www.youtube.com/embed/cl2hfVyNMUw"],
    Dragunov: ["https://www.youtube.com/embed/sJUL1-tfGDk"],
    Eddy: ["https://www.youtube.com/embed/cmrU6NaKJNo"],
    Fahkumram:[],
    Feng: ["https://www.youtube.com/embed/WN8gpBEZNic"],
    Heihachi: ["https://www.youtube.com/embed/80xUzZ8StDA"],
    Hwoarang: ["https://www.youtube.com/embed/bvjRn2-Vklw"],
    Jack: ["https://www.youtube.com/embed/7tYREaoHtIo"],
    Jin: ["https://www.youtube.com/embed/US0N87oWCzc"],
    Jun: ["https://www.youtube.com/embed/eTW2EHlA3WE"],
    Kazuya: ["https://www.youtube.com/embed/HxM_WEJM3AY"],
    King: ["https://www.youtube.com/embed/huIHYZIVG80"],
    Kuma: ["https://www.youtube.com/embed/QacppaF1L_g"],
    Lars: ["https://www.youtube.com/embed/i27J0ezT1XQ"],
    Law: ["https://www.youtube.com/embed/voKUjaB2nDA"],
    Lee: ["https://www.youtube.com/embed/HzwcP8LHN2E"],
    Leo: ["https://www.youtube.com/embed/XgeOTLcHoiQ"],
    Leroy: ["https://www.youtube.com/embed/GBKMqrgQH78"],
    Lidia: ["https://www.youtube.com/embed/ODItxfszB78"],
    Lili: ["https://www.youtube.com/embed/5FuCtwaSpAE"],
    Nina: ["https://www.youtube.com/embed/jmKSMNArC44"],
    Panda: ["https://www.youtube.com/embed/LOLXAA-eyTI"],
    Paul: ["https://www.youtube.com/embed/_ffNYhbtvPM"],
    Raven: ["https://www.youtube.com/embed/pCvnhfJ4Y4M"],
    Reina: ["https://www.youtube.com/embed/Cs7snBXr6bU"],
    Shaheen: ["https://www.youtube.com/embed/C3SzcZlVuf0"],
    Steve: ["https://www.youtube.com/embed/0r8FAejeTpA"],
    Victor: ["https://www.youtube.com/embed/dKgHNP-t9_U"],
    Xiaoyu: ["https://www.youtube.com/embed/O6Ri5CVdL3c"],
    Yoshimitsu: ["https://www.youtube.com/embed/wgC7Ul7B1Cw"],
    Zafina: ["https://www.youtube.com/embed/3Yi_YHPZyH0"],
  },
  Steve: {
    Alisa: ["https://www.youtube.com/embed/tnJz-Likl-M"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/KyHJxAr0JfQ"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/lSjesRz-ej8"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/Xy6SLAsHew4"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/ACcwhqbIfv4"],
    Claudio: ["https://www.youtube.com/embed/93GpW0X-T4g"],
    Clive: ["https://www.youtube.com/embed/t77hdliFtAk"],
    Devil: ["https://www.youtube.com/embed/LQioKg1qKfk"],
    Dragunov: ["https://www.youtube.com/embed/cl4cRi-53B8"],
    Eddy: ["https://www.youtube.com/embed/UXIF11sT8mo"],
    Fahkumram:["https://www.youtube.com/embed/fIowSOx172E"],
    Feng: ["https://www.youtube.com/embed/WkNiPmOIWEQ"],
    Heihachi: ["https://www.youtube.com/embed/V2rbtPmlJ5A"],
    Hwoarang: ["https://www.youtube.com/embed/s30L-GPAZUU"],
    Jack: ["https://www.youtube.com/embed/wemFDYlz1Rc"],
    Jin: ["https://www.youtube.com/embed/z82yJxzd4Po"],
    Jun: ["https://www.youtube.com/embed/s_C0tuGVBWA"],
    Kazuya: ["https://www.youtube.com/embed/XFKMr38Ej8c"],
    King: ["https://www.youtube.com/embed/QpfKNYu-JUc"],
    Kuma: ["https://www.youtube.com/embed/qMO_S7CFb1o"],
    Lars: ["https://www.youtube.com/embed/K52CnPap1zg"],
    Law: ["https://www.youtube.com/embed/YYLVlxkk430"],
    Lee: ["https://www.youtube.com/embed/2hF7wVatUkM"],
    Leo: ["https://www.youtube.com/embed/HNDkfNyQnys"],
    Leroy: ["https://www.youtube.com/embed/akIhEdVok1U"],
    Lidia: ["https://www.youtube.com/embed/iG2i8vCpv2M"],
    Lili: ["https://www.youtube.com/embed/rlez6al2tac"],
    Nina: ["https://www.youtube.com/embed/5N7ejPlvAA0"],
    Panda: ["https://www.youtube.com/embed/aOlj-6u67Fc"],
    Paul: ["https://www.youtube.com/embed/0vR8VqwXIpU"],
    Raven: ["https://www.youtube.com/embed/ypC3I50LK0c"],
    Reina: ["https://www.youtube.com/embed/CquIwouiAOA"],
    Shaheen: ["https://www.youtube.com/embed/0r8FAejeTpA"],
    Steve: ["https://www.youtube.com/embed/GbtzBJlQtpI"],
    Victor: ["https://www.youtube.com/embed/EsN8RY0vXYA"],
    Xiaoyu: ["https://www.youtube.com/embed/KCOZI_GPXJI"],
    Yoshimitsu: ["https://www.youtube.com/embed/-YrtFjLlzJQ"],
    Zafina: ["https://www.youtube.com/embed/bAlpu_XHklA"],
  },
  /*Template: {
    Alisa: [],
    Anna: [],
    Armour: [],
    Asuka: [],
    Azucena: [],
    Bryan: [],
    Claudio: [],
    Clive: [],
    Devil: [],
    Dragunov: [],
    Eddy: [],
    Fahkumram: [],
    Feng: [],
    Heihachi: [],
    Hwoarang: [],
    Jack: [],
    Jin: [],
    Jun: [],
    Kazuya: [],
    King: [],
    Kuma: [],
    Lars: [],
    Law: [],
    Lee: [],
    Leo: [],
    Leroy: [],
    Lidia: [],
    Lili: [],
    Nina: [],
    Panda: [],
    Paul: [],
    Raven: [],
    Reina: [],
    Shaheen: [],
    Steve: [],
    Victor: [],
    Xiaoyu: [],
    Yoshimitsu: [],
    Zafina: [],
},*/
  Victor: {
    Alisa: ["https://www.youtube.com/embed/oBjv_oL68VU"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/32c3GVtwSEM"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/HUEI92iL8Pw"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/cZyx5JWPRlQ"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/g4Sa1CdgHWM"],
    Claudio: ["https://www.youtube.com/embed/JaVnSh43sNo"],
    Clive: ["https://www.youtube.com/embed/NRazal7mLog"],
    Devil: ["https://www.youtube.com/embed/atzR3MKUrMo"],
    Dragunov: ["https://www.youtube.com/embed/RVsslHDTrLY"],
    Eddy: ["https://www.youtube.com/embed/wxokvJj7ghw"],
    Fahkumram:["https://www.youtube.com/embed/Tp2kzT_ZzmM"],
    Feng: ["https://www.youtube.com/embed/nKX562ofIGU"],
    Heihachi: ["https://www.youtube.com/embed/5vziUrbD490"],
    Hwoarang: ["https://www.youtube.com/embed/9Div4NHtv2Q"],
    Jack: ["https://www.youtube.com/embed/K1Hy9olmAiE"],
    Jin: ["https://www.youtube.com/embed/ng1tIkIJafQ"],
    Jun: ["https://www.youtube.com/embed/Q6xTgFPgJkU"],
    Kazuya: ["https://www.youtube.com/embed/xFkCpVkabW4"],
    King: ["https://www.youtube.com/embed/rHUbyoDvKwk"],
    Kuma: ["https://www.youtube.com/embed/AHauCZGrFuE"],
    Lars: ["https://www.youtube.com/embed/95Du9yRWMMQ"],
    Law: ["https://www.youtube.com/embed/uu6kNVgwuiQ"],
    Lee: ["https://www.youtube.com/embed/olazRnfpmks"],
    Leo: ["https://www.youtube.com/embed/OmgZ9pYo9qM"],
    Leroy: ["https://www.youtube.com/embed/lqTrEGrSL_8"],
    Lidia: ["https://www.youtube.com/embed/5pwmTsmFXIU"],
    Lili: ["https://www.youtube.com/embed/qzudEIV3U18"],
    Nina: ["https://www.youtube.com/embed/pg9pIgJjzDM"],
    Panda: ["https://www.youtube.com/embed/tlQ6Qa9g7gM"],
    Paul: ["https://www.youtube.com/embed/zm8C1Rk5xlc"],
    Raven: ["https://www.youtube.com/embed/4ZhRrW-cFhU"],
    Reina: ["https://www.youtube.com/embed/l3XcsTb0DvA"],
    Shaheen: ["https://www.youtube.com/embed/dKgHNP-t9_U"],
    Steve: ["https://www.youtube.com/embed/EsN8RY0vXYA"],
    Victor: ["https://www.youtube.com/embed/DE26tS33D1I"],
    Xiaoyu: ["https://www.youtube.com/embed/-vVOxdPstsc"],
    Yoshimitsu: ["https://www.youtube.com/embed/IeMeD759A7A"],
    Zafina: ["https://www.youtube.com/embed/9r7BIJlGeIc"],
  },
  Xiaoyu: {
    Alisa: ["https://www.youtube.com/embed/g_8Y5BmM3TI"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/bUhXhbCJNeE"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/K-klmyOxGos"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/KOVwxOqRt30"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/iarFb5waUy4"],
    Claudio: ["https://www.youtube.com/embed/F16D0a0acUc"],
    Clive: ["https://www.youtube.com/embed/xeju4jqq9uc"],
    Devil: ["https://www.youtube.com/embed/SgQkiAemiMo"],
    Dragunov: ["https://www.youtube.com/embed/CMoM_6T2WUE"],
    Eddy: ["https://www.youtube.com/embed/L-syT6BJ2dc"],
    Fahkumram:["https://www.youtube.com/embed/gtkNuxBEWMg"],
    Feng: ["https://www.youtube.com/embed/YI4ypF4N9WQ"],
    Heihachi: ["https://www.youtube.com/embed/5Yd98XkZnm4"],
    Hwoarang: ["https://www.youtube.com/embed/ReQu8jftJIg"],
    Jack: ["https://www.youtube.com/embed/C-OkV9Im6vk"],
    Jin: ["https://www.youtube.com/embed/kX59WBCxiUQ"],
    Jun: ["https://www.youtube.com/embed/6blPjp1cDBI"],
    Kazuya: ["https://www.youtube.com/embed/5R3R9zVHyLE"],
    King: ["https://www.youtube.com/embed/eNif-xgNz2c"],
    Kuma: ["https://www.youtube.com/embed/Qg-BN9SfWHs"],
    Lars: ["https://www.youtube.com/embed/5rT-R6Lst2M"],
    Law: ["https://www.youtube.com/embed/pFhsdJQAUaA"],
    Lee: ["https://www.youtube.com/embed/0rc6o3jk1JM"],
    Leo: ["https://www.youtube.com/embed/U637FKS9c-c"],
    Leroy: ["https://www.youtube.com/embed/UEdq_LqW5i0"],
    Lidia: ["https://www.youtube.com/embed/O3WCk5zGs_I"],
    Lili: ["https://www.youtube.com/embed/XE_G1-Vdwf4"],
    Nina: ["https://www.youtube.com/embed/r_U3deGuFYw"],
    Panda: ["https://www.youtube.com/embed/8p9bv0OpF1Q"],
    Paul: ["https://www.youtube.com/embed/hLTYsC_k9Rs"],
    Raven: ["https://www.youtube.com/embed/cOhbc8PcRhs"],
    Reina: ["https://www.youtube.com/embed/eK2eJgW6Jyw"],
    Shaheen: ["https://www.youtube.com/embed/O6Ri5CVdL3c"],
    Steve: ["https://www.youtube.com/embed/KCOZI_GPXJI"],
    Victor: ["https://www.youtube.com/embed/-vVOxdPstsc"],
    Xiaoyu: ["https://www.youtube.com/embed/NxovFRWM7bY"],
    Yoshimitsu: ["https://www.youtube.com/embed/N2gfbmUG-vM"],
    Zafina: ["https://www.youtube.com/embed/FQCr2WbwwS0"],
  },
  Yoshimitsu: {
    Alisa: ["https://www.youtube.com/embed/tqwNO8ZsalE"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/A7ZwKUXdiBc"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/Holhii16f44"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/X3U1ECIxud8"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/kzbocP-KK6A"],
    Claudio: ["https://www.youtube.com/embed/in-t33vibp8"],
    Clive: ["https://www.youtube.com/embed/gUczI_sxqEc"],
    Devil: ["https://www.youtube.com/embed/ix-Rmq-3Vsk"],
    Dragunov: ["https://www.youtube.com/embed/AkMPpx_SdBA"],
    Eddy: ["https://www.youtube.com/embed/YiNYHv8_6ok"],
    Fahkumram:["https://www.youtube.com/embed/O5zWVvhty3Y"],
    Feng: ["https://www.youtube.com/embed/fp_DEYSHt-M"],
    Heihachi: ["https://www.youtube.com/embed/VZhKPprtL3Y"],
    Hwoarang: ["https://www.youtube.com/embed/HF613P8mylQ"],
    Jack: ["https://www.youtube.com/embed/JAOE3ZHaKu0"],
    Jin: ["https://www.youtube.com/embed/Cr6LZkjhMn4"],
    Jun: ["https://www.youtube.com/embed/5sMH1nu5Mtc"],
    Kazuya: ["https://www.youtube.com/embed/_YORKMfBxzE"],
    King: ["https://www.youtube.com/embed/up8iv6Se_VQ"],
    Kuma: ["https://www.youtube.com/embed/YqGX6CYCvpg"],
    Lars: ["https://www.youtube.com/embed/2fMZWkztGcs"],
    Law: ["https://www.youtube.com/embed/bSR5Kr5e08c"],
    Lee: ["https://www.youtube.com/embed/DQwtSWqt1wc"],
    Leo: ["https://www.youtube.com/embed/fTzzGV7nsiQ"],
    Leroy: ["https://www.youtube.com/embed/W7TJ7TgiCFo"],
    Lidia: ["https://www.youtube.com/embed/iRRtajwiPzY"],
    Lili: ["https://www.youtube.com/embed/9wSHDi4xVJs"],
    Nina: ["https://www.youtube.com/embed/MwO2s1F31Mg"],
    Panda: ["https://www.youtube.com/embed/YZYRsp3xcAE"],
    Paul: ["https://www.youtube.com/embed/ah6N0wkNE3M"],
    Raven: ["https://www.youtube.com/embed/R2kSBptlUQA"],
    Reina: ["https://www.youtube.com/embed/g-ht9nt3cQE"],
    Shaheen: ["https://www.youtube.com/embed/wgC7Ul7B1Cw"],
    Steve: ["https://www.youtube.com/embed/-YrtFjLlzJQ"],
    Victor: ["https://www.youtube.com/embed/IeMeD759A7A"],
    Xiaoyu: ["https://www.youtube.com/embed/N2gfbmUG-vM"],
    Yoshimitsu: ["https://www.youtube.com/embed/okjKQY-jS1g"],
    Zafina: ["https://www.youtube.com/embed/Oy4BfMKjxQ4"],
  },
  Zafina: {
    Alisa: ["https://www.youtube.com/embed/rEQ4Gnf8Hfo"], // Add video links or data here
    Anna: ["https://www.youtube.com/embed/ebrH4Pj0F6Y"],
    Armour:[],
    Asuka: ["https://www.youtube.com/embed/sqmMfPD6WMM"], // Add video links or data here
    Azucena: ["https://www.youtube.com/embed/MSrbzLMUhzQ"], // Add video links or data here
    Bryan: ["https://www.youtube.com/embed/3O1iukSaWSU"],
    Claudio: ["https://www.youtube.com/embed/5uxPknfXnG4"],
    Clive: ["https://www.youtube.com/embed/KpzTubVfKS4"],
    Devil: ["https://www.youtube.com/embed/0d1BtDOsNgk"],
    Dragunov: ["https://www.youtube.com/embed/IpBcfZ87vqM"],
    Eddy: ["https://www.youtube.com/embed/BJTAItSWk5I"],
    Fahkumram:["https://www.youtube.com/embed/cLetl1KhlJQ"],
    Feng: ["https://www.youtube.com/embed/k21l8kfWwyQ"],
    Heihachi: ["https://www.youtube.com/embed/vEqi7Jd_Uxc"],
    Hwoarang: ["https://www.youtube.com/embed/TYRwY5nJpjY"],
    Jack: ["https://www.youtube.com/embed/MciyqEIZQkY"],
    Jin: ["https://www.youtube.com/embed/WwUKCOFIe04"],
    Jun: ["https://www.youtube.com/embed/kSy9u1P9onw"],
    Kazuya: ["https://www.youtube.com/embed/h-TcuAWV8ik"],
    King: ["https://www.youtube.com/embed/lwNDRCJCIwA"],
    Kuma: ["https://www.youtube.com/embed/7DlaStMeIBM"],
    Lars: ["https://www.youtube.com/embed/6f7bf5QGgEA"],
    Law: ["https://www.youtube.com/embed/aM9ZkijYSzM"],
    Lee: ["https://www.youtube.com/embed/Bj3OeCooaSw"],
    Leo: ["https://www.youtube.com/embed/z3p9ch0dxFU"],
    Leroy: ["https://www.youtube.com/embed/TahtBop1mdI"],
    Lidia: ["https://www.youtube.com/embed/Pam_zy3TnXg"],
    Lili: ["https://www.youtube.com/embed/UBV4qrgTsOo"],
    Nina: ["https://www.youtube.com/embed/ryEYjjruouY"],
    Panda: ["https://www.youtube.com/embed/ERy-51rjpMw"],
    Paul: ["https://www.youtube.com/embed/sE6sGW4gV-U"],
    Raven: ["https://www.youtube.com/embed/aWCTS1bNmHQ"],
    Reina: ["https://www.youtube.com/embed/1-AsiTCbq1w"],
    Shaheen: ["https://www.youtube.com/embed/3Yi_YHPZyH0"],
    Steve: ["https://www.youtube.com/embed/bAlpu_XHklA"],
    Victor: ["https://www.youtube.com/embed/9r7BIJlGeIc"],
    Xiaoyu: ["https://www.youtube.com/embed/FQCr2WbwwS0"],
    Yoshimitsu: ["https://www.youtube.com/embed/Oy4BfMKjxQ4"],
    Zafina: ["https://www.youtube.com/embed/S6NncjK6I5A"],
  },
};
